# frozen_string_literal: true

require "digest"
require "fileutils"
require "json"
require "securerandom"
require "time"

require_relative "errors"

module Rubernetes
  module Runtime
    class MicroVM < Runtime
      # Durable identity ledger (spec/node/runtime.md 5.8.12).  Every VM
      # instance, whether cold-booted or restored from the base snapshot,
      # receives a freshly generated identity: VM id, Pod sandbox id,
      # subject id, capability id, request id, vsock session (UDS path +
      # session key + nonce), guest entropy, hostname, machine id, network
      # identity (MAC, IP, routes), workspace id, policy digest, artifact
      # digest and revocation epoch.  Numeric identities that the kernel
      # cannot re-issue (jail UID/GID, guest CID) are allocated from
      # monotonically increasing counters and are never reused while any
      # record that holds them is not released.  The ledger is an
      # append-only JSON-lines file with fsync; the in-memory view is
      # rebuilt from it on start.
      class IdentityLedger
        UID_BASE = 200_000
        UID_LIMIT = 300_000
        CID_BASE = 3
        MAC_PREFIX = [0x06, 0x00].freeze
        # Values generated by the ledger itself: issued exactly once, ever.
        ROTATED_FIELDS = %w[vm_id subject_id capability_id request_id vsock_uds_path vsock_session_key vsock_nonce entropy hostname machine_id
                            mac_address workspace_id credential_id policy_digest policy_generation jail_uid guest_cid].freeze

        Record = Struct.new(:vm_id, :sandbox_id, :state, :fields, :created_at, :released_at, keyword_init: true) do
          def to_h
            {"vm_id" => vm_id, "sandbox_id" => sandbox_id, "state" => state, "fields" => fields, "created_at" => created_at, "released_at" => released_at}
          end
        end

        def initialize(path, fsync: true, clock: -> { Time.now.utc })
          @path = path
          @fsync = fsync
          @clock = clock
          @mutex = Mutex.new
          @records = {}
          @next_uid = UID_BASE
          @next_cid = CID_BASE
          @policy_generation = 0
          @revocation_epoch = 0
          @seen = Hash.new { |hash, key| hash[key] = {} }
          FileUtils.mkdir_p(File.dirname(@path))
          replay!
        end

        attr_reader :path, :revocation_epoch

        # Allocates a complete new identity for +sandbox_id+.  +network+ is
        # nil until the network layer has leased an address; ip/routes are
        # then bound with bind_network.
        def allocate(sandbox_id:, runtime_class:, artifact_digest:, policy_digest:, request_id: nil, workspace_id: nil)
          @mutex.synchronize do
            raise IdentityError, "sandbox #{sandbox_id} already holds a live identity" if @records.values.any? { |record| record.sandbox_id == sandbox_id && record.state == "live" }

            uid = @next_uid
            raise IdentityError, "jail UID range exhausted" if uid >= UID_LIMIT

            cid = @next_cid
            @next_uid += 1
            @next_cid += 1
            @policy_generation += 1
            vm_id = "vm-#{SecureRandom.hex(8)}"
            fields = {
              "vm_id" => vm_id,
              "sandbox_id" => sandbox_id,
              "runtime_class" => runtime_class,
              "subject_id" => "subject-#{SecureRandom.hex(16)}",
              "capability_id" => "cap-#{SecureRandom.hex(16)}",
              "request_id" => request_id || "req-#{SecureRandom.hex(16)}",
              "vsock_uds_path" => "/run/vsock-#{SecureRandom.hex(6)}.sock",
              "vsock_session_key" => SecureRandom.hex(32),
              "vsock_nonce" => SecureRandom.hex(16),
              "entropy" => SecureRandom.hex(32),
              "hostname" => "vm-#{SecureRandom.hex(6)}",
              "machine_id" => SecureRandom.hex(16),
              "mac_address" => (MAC_PREFIX + Array.new(4) { SecureRandom.random_number(256) }).map { |byte| format("%02x", byte) }.join(":"),
              "ip" => nil,
              "routes" => [],
              "workspace_id" => workspace_id || "ws-#{SecureRandom.hex(8)}",
              "credential_id" => "cred-#{SecureRandom.hex(16)}",
              # The per-VM policy digest binds the policy content to this
              # VM's generation, so a stale ACK for an earlier clone never
              # matches.
              "policy_content_digest" => policy_digest,
              "policy_digest" => Digest::SHA256.hexdigest("#{policy_digest}:#{@policy_generation}"),
              "policy_generation" => @policy_generation,
              "artifact_digest" => artifact_digest,
              "revocation_epoch" => @revocation_epoch,
              "jail_uid" => uid,
              "jail_gid" => uid,
              "guest_cid" => cid
            }
            ensure_unique!(fields)
            record = Record.new(vm_id: vm_id, sandbox_id: sandbox_id, state: "live", fields: fields, created_at: @clock.call.iso8601(6), released_at: nil)
            append!("allocate", record)
            @records[vm_id] = record
            record
          end
        end

        def bind_network(vm_id, ip:, routes: [], gateway: nil, prefix_length: nil)
          @mutex.synchronize do
            record = live!(vm_id)
            raise IdentityError, "IP #{ip} is held by a live identity" if ip && @records.values.any? { |other| other.state == "live" && other.vm_id != vm_id && other.fields["ip"] == ip }

            record.fields = record.fields.merge("ip" => ip, "routes" => routes, "gateway" => gateway, "prefix_length" => prefix_length)
            append!("bind_network", record)
            record
          end
        end

        def revoke!
          @mutex.synchronize do
            @revocation_epoch += 1
            append!("revoke", Record.new(vm_id: nil, sandbox_id: nil, state: "epoch", fields: {"revocation_epoch" => @revocation_epoch}, created_at: @clock.call.iso8601(6)))
            @revocation_epoch
          end
        end

        def release(vm_id)
          @mutex.synchronize do
            record = @records[vm_id]
            return nil if record.nil? || record.state == "released"

            record.state = "released"
            record.released_at = @clock.call.iso8601(6)
            append!("release", record)
            record
          end
        end

        def record(vm_id)
          @mutex.synchronize { @records[vm_id] }
        end

        def live
          @mutex.synchronize { @records.values.select { |record| record.state == "live" }.map(&:dup) }
        end

        def all
          @mutex.synchronize { @records.values.map(&:dup) }
        end

        # Audit: the number of identity values that appear in more than one
        # record, per rotated field.  Zero everywhere is the M7 requirement.
        def reuse_report
          @mutex.synchronize do
            report = {}
            ROTATED_FIELDS.each do |field|
              values = @records.values.map { |record| record.fields[field] }.compact
              duplicates = values.tally.select { |_value, count| count > 1 }
              report[field] = {"records" => values.length, "distinct" => values.uniq.length, "reused" => duplicates.length}
            end
            report
          end
        end

        private

        def live!(vm_id)
          record = @records[vm_id]
          raise IdentityError, "unknown VM identity #{vm_id}" if record.nil?
          raise IdentityError, "VM identity #{vm_id} is released" unless record.state == "live"

          record
        end

        def ensure_unique!(fields)
          ROTATED_FIELDS.each do |field|
            value = fields[field]
            next if value.nil?
            raise IdentityError, "identity value for #{field} was issued before" if @seen[field].key?(value)
          end
          ROTATED_FIELDS.each { |field| @seen[field][fields[field]] = true unless fields[field].nil? }
        end

        def append!(event, record)
          line = JSON.generate({"event" => event, "at" => @clock.call.iso8601(6), "record" => record.to_h,
                                "next_uid" => @next_uid, "next_cid" => @next_cid, "policy_generation" => @policy_generation, "revocation_epoch" => @revocation_epoch})
          File.open(@path, File::WRONLY | File::APPEND | File::CREAT, 0o600) do |file|
            file.write(line + "\n")
            file.fsync if @fsync
          end
        end

        def replay!
          return unless File.file?(@path)

          File.foreach(@path) do |line|
            next if line.strip.empty?

            entry = JSON.parse(line)
            @next_uid = [@next_uid, entry.fetch("next_uid", UID_BASE)].max
            @next_cid = [@next_cid, entry.fetch("next_cid", CID_BASE)].max
            @policy_generation = [@policy_generation, entry.fetch("policy_generation", 0)].max
            @revocation_epoch = [@revocation_epoch, entry.fetch("revocation_epoch", 0)].max
            value = entry.fetch("record")
            next if value["vm_id"].nil?

            record = Record.new(vm_id: value["vm_id"], sandbox_id: value["sandbox_id"], state: value["state"], fields: value["fields"],
                                created_at: value["created_at"], released_at: value["released_at"])
            @records[record.vm_id] = record
            ROTATED_FIELDS.each { |field| @seen[field][record.fields[field]] = true unless record.fields[field].nil? }
          end
        rescue JSON::ParserError => error
          raise IdentityError, "identity ledger #{@path} is corrupt: #{error.message}"
        end
      end
    end
  end
end
