# frozen_string_literal: true

require "fiddle"
require_relative "bpf"
require_relative "error"

module Rubernetes
  module Platform
    module Linux
      # The cgroup v2 device controller as runc applies it: an OCI device
      # rule list is reduced by the cgroup v1 "devices.list" emulator
      # (opencontainers/cgroups devices/devices_emulator.go) and compiled into
      # a BPF_PROG_TYPE_CGROUP_DEVICE program (devices/devicefilter.go, itself
      # from crun's ebpf.c) that the kernel runs on every open(2)/mknod(2) of
      # a device node by a task in the cgroup.  The instruction stream is byte
      # for byte the one runc v1.4.3 produces (test/fixtures/runc/
      # device-filter-v1.4.3.json is generated by that code: see
      # test/conformance/runc/device_filter_oracle).
      #
      # Without this a root container -- no user namespace, /dev on a tmpfs
      # without nodev -- could mknod a host block device and read it.
      module DeviceCgroup
        class Error < StandardError; end

        WILDCARD = -1
        # Kernel MODULE_LICENSE string runc passes; no GPL-only helper is used.
        LICENSE = "Apache"
        # Program name (bpf_attr.prog_name, 15 bytes) the detach path matches.
        PROGRAM_NAME = "rbn_devcg"

        # include/uapi/linux/bpf.h
        BPF_DEVCG_ACC_MKNOD = 1
        BPF_DEVCG_ACC_READ = 2
        BPF_DEVCG_ACC_WRITE = 4
        BPF_DEVCG_DEV_BLOCK = 1
        BPF_DEVCG_DEV_CHAR = 2
        MAX_UINT32 = 0xFFFF_FFFF

        # devices/config Permissions: a cgroup v1 "rwm" string with set
        # operations; every operation canonicalises to "r" "w" "m" order.
        module Permissions
          READ = 1
          WRITE = 2
          MKNOD = 4

          module_function

          def to_set(value)
            set = 0
            String(value).each_char do |char|
              case char
              when "r" then set |= READ
              when "w" then set |= WRITE
              when "m" then set |= MKNOD
              end
            end
            set
          end

          def from_set(set)
            text = +""
            text << "r" if set & READ == READ
            text << "w" if set & WRITE == WRITE
            text << "m" if set & MKNOD == MKNOD
            text.freeze
          end

          def union(left, right) = from_set(to_set(left) | to_set(right))
          def difference(left, right) = from_set(to_set(left) & ~to_set(right))
          def intersection(left, right) = from_set(to_set(left) & to_set(right))
          def empty?(value) = String(value).empty?
          def valid?(value) = String(value) == from_set(to_set(value))
        end

        # An OCI linux.resources.devices entry (devices/config Rule).  +type+
        # is "a" (wildcard), "b" or "c"; a wildcard major/minor is -1.
        Rule = Data.define(:type, :major, :minor, :permissions, :allow) do
          def self.from(value)
            return value if value.is_a?(self)

            hash = value.to_h.transform_keys(&:to_s)
            new(type: String(hash.fetch("type")), major: Integer(hash.fetch("major", WILDCARD)),
                minor: Integer(hash.fetch("minor", WILDCARD)), permissions: String(hash.fetch("permissions") { hash.fetch("access", "") }),
                allow: hash.fetch("allow") == true)
          end

          def wildcard? = type == "a"

          def to_h
            {"type" => type, "major" => major, "minor" => minor, "access" => permissions, "allow" => allow}
          end

          # Rule#CgroupString
          def cgroup_string
            "#{type} #{major == WILDCARD ? "*" : major}:#{minor == WILDCARD ? "*" : minor} #{permissions}"
          end
        end

        # runc libcontainer/specconv AllowedDevices, in runc's order: every
        # container may mknod any node (but not open what it made) and use
        # the standard character devices, the pts namespace, ptmx and tun.
        DEFAULT_RULES = [
          Rule.new(type: "c", major: WILDCARD, minor: WILDCARD, permissions: "m", allow: true),
          Rule.new(type: "b", major: WILDCARD, minor: WILDCARD, permissions: "m", allow: true),
          Rule.new(type: "c", major: 1, minor: 3, permissions: "rwm", allow: true),   # /dev/null
          Rule.new(type: "c", major: 1, minor: 8, permissions: "rwm", allow: true),   # /dev/random
          Rule.new(type: "c", major: 1, minor: 7, permissions: "rwm", allow: true),   # /dev/full
          Rule.new(type: "c", major: 5, minor: 0, permissions: "rwm", allow: true),   # /dev/tty
          Rule.new(type: "c", major: 1, minor: 5, permissions: "rwm", allow: true),   # /dev/zero
          Rule.new(type: "c", major: 1, minor: 9, permissions: "rwm", allow: true),   # /dev/urandom
          Rule.new(type: "c", major: 136, minor: WILDCARD, permissions: "rwm", allow: true), # /dev/pts/*
          Rule.new(type: "c", major: 5, minor: 2, permissions: "rwm", allow: true),   # /dev/ptmx
          Rule.new(type: "c", major: 10, minor: 200, permissions: "rwm", allow: true) # /dev/net/tun
        ].freeze

        DENY_ALL = Rule.new(type: "a", major: WILDCARD, minor: WILDCARD, permissions: "rwm", allow: false)
        ALLOW_ALL = Rule.new(type: "a", major: WILDCARD, minor: WILDCARD, permissions: "rwm", allow: true)

        module_function

        # The rule list containerd's CRI plugin hands runc for a container:
        # deny everything (allow everything when privileged), the container's
        # own devices (CRI Device permissions verbatim), then runc appends
        # AllowedDevices.
        def rules_for(privileged: false, devices: [])
          [privileged ? ALLOW_ALL : DENY_ALL] + Array(devices).map { |device| Rule.from(device) } + DEFAULT_RULES
        end

        # devicefilter.go deviceFilter: the instruction stream and license.
        def compile(rules)
          emulator = Emulator.new
          rules.each { |rule| emulator.apply(Rule.from(rule)) }
          clean = emulator.rules
          program = Program.new(default_allow: emulator.blacklist?)
          clean.each_with_index do |rule, index|
            if rule.wildcard?
              if index != 0 || rule.allow != emulator.blacklist?
                raise Error, "[internal error] emulated cgroupv2 devices ruleset had bad wildcard at idx #{index} (#{rule.cgroup_string})"
              end
              next
            end
            if rule.allow == program.default_allow
              raise Error, "[internal error] emulated cgroupv2 devices ruleset had no-op rule at idx #{index} (#{rule.cgroup_string})"
            end

            program.append_rule(rule)
          end
          [program.finalize, LICENSE]
        end

        def encode(instructions)
          instructions.map(&:to_binary).join.b
        end

        # devices_emulator.go: the cgroup v1 devices.list state machine.  An
        # "a" rule resets the emulator into deny-list (allow) or allow-list
        # (deny) mode; other rules add or remove exceptions, and removing part
        # of a wildcard exception is refused (cgroup v1 would silently ignore
        # it, leaving the hole open).
        class Emulator
          Meta = Data.define(:node, :major, :minor) do
            # fmt %v of the Go struct: the Type is a rune.
            def to_s = "{#{node.ord} #{major} #{minor}}"
          end

          attr_reader :default_allow

          def initialize
            @default_allow = false
            @rules = {}
          end

          def blacklist? = @default_allow
          def allow_all? = blacklist? && @rules.empty?

          def apply(rule)
            rule = Rule.from(rule)
            unless %w[a b c].include?(rule.type)
              raise Error, "cannot add rule [config.Rule{Type:#{rule.type.ord}, Major:#{rule.major}, Minor:#{rule.minor}, " \
                           "Permissions:#{rule.permissions.inspect}, Allow:#{rule.allow}}] with non-cgroup type '#{rule.type}'"
            end

            inner = rule.wildcard? ? nil : [Meta.new(node: rule.type, major: rule.major, minor: rule.minor), rule.permissions]
            rule.allow ? allow(inner) : deny(inner)
          end

          # Rules(): the minimum rule list that takes a deny-all cgroup to
          # this state (Transition from an empty emulator).
          def rules
            transition = []
            transition << Rule.new(type: "a", major: WILDCARD, minor: WILDCARD, permissions: "rwm", allow: true) if @default_allow
            ordered_entries.each do |meta, perms|
              next if Permissions.empty?(perms)

              transition << Rule.new(type: meta.node, major: meta.major, minor: meta.minor,
                                     permissions: Permissions.difference(perms, ""), allow: !@default_allow)
            end
            transition
          end

          private

          def ordered_entries
            @rules.sort_by { |meta, _| [meta.major, meta.minor, meta.node.ord] }
          end

          def allow(inner)
            if inner.nil?
              @default_allow = true
              @rules = {}
              return
            end
            @default_allow ? remove_rule(*inner, "unable to remove 'deny' exception") : add_rule(*inner)
          end

          def deny(inner)
            if inner.nil?
              @default_allow = false
              @rules = {}
              return
            end
            @default_allow ? add_rule(*inner) : remove_rule(*inner, "unable to remove 'allow' exception")
          end

          def add_rule(meta, perms)
            @rules[meta] = Permissions.union(perms, @rules[meta] || "")
          end

          def remove_rule(meta, perms, wrap)
            [Meta.new(node: meta.node, major: WILDCARD, minor: meta.minor),
             Meta.new(node: meta.node, major: meta.major, minor: WILDCARD),
             Meta.new(node: meta.node, major: WILDCARD, minor: WILDCARD)].each do |partial|
              next if partial == meta

              partial_perms = @rules[partial] || ""
              next if Permissions.empty?(Permissions.intersection(partial_perms, perms))

              raise Error, "#{wrap}: requested rule [#{meta} #{perms}] not supported by devices cgroupv1 " \
                           "(cannot punch hole in existing wildcard rule [#{partial} #{partial_perms}])"
            end
            remaining = Permissions.difference(@rules[meta] || "", perms)
            if Permissions.empty?(remaining)
              @rules.delete(meta)
            else
              @rules[meta] = remaining
            end
          end
        end

        # devicefilter.go program: one block per clean rule, each jumping to
        # the next block when the context does not match, then the default
        # verdict.  Registers as runc: R1 = struct bpf_cgroup_dev_ctx,
        # R2 = type, R3 = access, R4 = major, R5 = minor.
        class Program
          # eBPF opcodes (include/uapi/linux/bpf_common.h + bpf.h)
          LDX_MEM_W = 0x61  # BPF_LDX | BPF_MEM | BPF_W
          ALU_AND_K = 0x54  # BPF_ALU | BPF_AND | BPF_K
          ALU_RSH_K = 0x74  # BPF_ALU | BPF_RSH | BPF_K
          ALU_MOV_X = 0xbc  # BPF_ALU | BPF_MOV | BPF_X
          ALU_MOV_K = 0xb4  # BPF_ALU | BPF_MOV | BPF_K
          JMP_JNE_K = 0x55  # BPF_JMP | BPF_JNE | BPF_K
          JMP_JNE_X = 0x5d  # BPF_JMP | BPF_JNE | BPF_X
          JMP_EXIT = 0x95   # BPF_JMP | BPF_EXIT

          attr_reader :default_allow

          def initialize(default_allow:)
            @default_allow = default_allow
            @finalized = false
            @instructions = [
              instruction(LDX_MEM_W, 2, 1, 0, 0),        # R2 <- ctx->access_type
              instruction(ALU_AND_K, 2, 0, 0, 0xFFFF),   # R2 &= 0xFFFF (type)
              instruction(LDX_MEM_W, 3, 1, 0, 0),        # R3 <- ctx->access_type
              instruction(ALU_RSH_K, 3, 0, 0, 16),       # R3 >>= 16 (access)
              instruction(LDX_MEM_W, 4, 1, 4, 0),        # R4 <- ctx->major
              instruction(LDX_MEM_W, 5, 1, 8, 0)         # R5 <- ctx->minor
            ]
          end

          def append_rule(rule)
            raise Error, "the program is finalized" if @finalized

            bpf_type = case rule.type
                       when "c" then BPF_DEVCG_DEV_CHAR
                       when "b" then BPF_DEVCG_DEV_BLOCK
                       else raise Error, "invalid type #{rule.type.inspect}"
                       end
            raise Error, "invalid major #{rule.major}" if rule.major > MAX_UINT32
            # (runc prints the major here too)
            raise Error, "invalid minor #{rule.major}" if rule.minor > MAX_UINT32

            has_major = rule.major >= 0
            has_minor = rule.minor >= 0
            bpf_access = 0
            rule.permissions.each_char do |char|
              case char
              when "r" then bpf_access |= BPF_DEVCG_ACC_READ
              when "w" then bpf_access |= BPF_DEVCG_ACC_WRITE
              when "m" then bpf_access |= BPF_DEVCG_ACC_MKNOD
              else raise Error, "unknown device access #{char.ord}"
              end
            end
            has_access = bpf_access != (BPF_DEVCG_ACC_READ | BPF_DEVCG_ACC_WRITE | BPF_DEVCG_ACC_MKNOD)

            # Every jump in the block targets the next block's first
            # instruction; the offset is resolved from the block length.
            block = []
            block << [JMP_JNE_K, 2, 0, :next, bpf_type]
            if has_access
              block << [ALU_MOV_X, 1, 3, 0, 0]
              block << [ALU_AND_K, 1, 0, 0, bpf_access]
              block << [JMP_JNE_X, 1, 3, :next, 0]
            end
            block << [JMP_JNE_K, 4, 0, :next, signed32(rule.major)] if has_major
            block << [JMP_JNE_K, 5, 0, :next, signed32(rule.minor)] if has_minor
            block.concat(accept_block(rule.allow))
            block.each_with_index do |(code, dst, src, offset, imm), index|
              offset = block.length - index - 1 if offset == :next
              @instructions << instruction(code, dst, src, offset, imm)
            end
            true
          end

          def finalize
            @instructions.concat(accept_block(@default_allow).map { |fields| instruction(*fields) })
            @finalized = true
            @instructions.freeze
          end

          private

          def accept_block(accept)
            [[ALU_MOV_K, 0, 0, 0, accept ? 1 : 0], [JMP_EXIT, 0, 0, 0, 0]]
          end

          def instruction(code, destination, source, offset, immediate)
            BPF::Instruction.new(code: code, destination: destination, source: source, offset: offset, immediate: immediate)
          end

          # int32(rule.Major): a value in [2^31, 2^32) keeps its bits.
          def signed32(value)
            value &= MAX_UINT32
            value >= 0x8000_0000 ? value - 0x1_0000_0000 : value
          end
        end

        # Loads a compiled filter and attaches it to a container cgroup
        # (BPF_F_ALLOW_MULTI, like runc: programs on the ancestors keep
        # running).  The program bytes depend only on the rule set, and
        # loading (verifier + info readback) costs ~1.5 ms against ~0.02 ms
        # for the attach, so one loaded program per rule set is kept and
        # attached to every cgroup with those rules; the cgroup holds its own
        # reference, so a detach after an agent restart finds the program
        # again by querying the cgroup.
        class Attacher
          # include/uapi/asm-generic/fcntl.h (x86_64/arm64 share the value).
          O_DIRECTORY = 0o200000
          # Fits BPF_OBJ_NAME_LEN with the kernel's terminating NUL.
          NAME = PROGRAM_NAME
          # Distinct rule sets kept loaded (LRU); an evicted program's
          # descriptor is closed, which does not detach it anywhere.
          PROGRAM_CACHE_LIMIT = 64

          def initialize(bpf: nil, cache_limit: PROGRAM_CACHE_LIMIT)
            @bpf = bpf
            @cache_limit = Integer(cache_limit)
            @programs = {}
            @mutex = Mutex.new
          end

          def cached_rule_sets = @mutex.synchronize { @programs.length }

          def bpf
            @bpf ||= BPF.new
          end

          # Fails closed at startup: the kernel must accept the default
          # allow-list program (CONFIG_CGROUP_BPF, BPF_PROG_TYPE_CGROUP_DEVICE)
          # or no container can be isolated.
          def validate!
            instructions, license = DeviceCgroup.compile(DeviceCgroup.rules_for)
            program = load(instructions, license, resource_id: "bpf:device-filter:probe")
            program.close
            true
          rescue Linux::Error, BPF::VerifierError => error
            raise Error, "cgroup device filter program rejected by the kernel: #{error.message}"
          end

          # Attaches the filter for +rules+ to the cgroup directory +cgroup_path+;
          # returns the kernel program id.
          def attach(cgroup_path, rules)
            path = File.expand_path(String(cgroup_path))
            program = program_for(rules)
            with_cgroup(path) do |directory|
              bpf.prog_attach(target_fd: directory.fileno, program: program, attach_type: BPF::BPF_CGROUP_DEVICE,
                              flags: BPF::BPF_F_ALLOW_MULTI, resource_id: "bpf:device-filter:attach:#{path}")
            end
            program.id
          rescue Linux::Error => error
            raise Error, "cannot attach the device filter to #{cgroup_path}: #{error.message}"
          end

          # Closes every cached program descriptor (attached programs stay).
          def close
            @mutex.synchronize do
              @programs.each_value(&:close)
              @programs.clear
            end
            true
          end

          # Detaches every program this class attached to +cgroup_path+ and
          # returns their ids.  A cgroup that no longer exists has nothing
          # attached (the kernel released its programs with it).
          def detach(cgroup_path)
            path = File.expand_path(String(cgroup_path))
            detached = []
            with_cgroup(path) do |directory|
              bpf.prog_query(target_fd: directory.fileno, attach_type: BPF::BPF_CGROUP_DEVICE,
                             resource_id: "bpf:device-filter:query:#{path}").each do |id|
                fd = begin
                  bpf.prog_get_fd_by_id(id, resource_id: "bpf:device-filter:detach:#{path}")
                rescue Linux::Error => error
                  raise unless error.errno == Errno::ENOENT::Errno

                  next
                end
                begin
                  next unless bpf.program_info(fd, resource_id: "bpf:device-filter:detach:#{path}").fetch(:name) == NAME

                  bpf.prog_detach(target_fd: directory.fileno, program: fd, attach_type: BPF::BPF_CGROUP_DEVICE,
                                  resource_id: "bpf:device-filter:detach:#{path}")
                  detached << id
                ensure
                  IO.for_fd(fd).close
                end
              end
            end
            detached
          rescue Errno::ENOENT
            []
          rescue Linux::Error => error
            raise Error, "cannot detach the device filter from #{cgroup_path}: #{error.message}"
          end

          # Ids of the device programs attached to the cgroup, in attach order.
          def attached(cgroup_path)
            with_cgroup(File.expand_path(String(cgroup_path))) do |directory|
              bpf.prog_query(target_fd: directory.fileno, attach_type: BPF::BPF_CGROUP_DEVICE)
            end
          end

          private

          # The loaded program for a rule set, compiled and loaded on first
          # use.  The key is the canonical rule list (order matters: it is
          # what the emulator sees).
          def program_for(rules)
            key = Array(rules).map { |rule| Rule.from(rule).to_h }.freeze
            @mutex.synchronize do
              cached = @programs.delete(key)
              if cached
                @programs[key] = cached
                return cached
              end

              instructions, license = DeviceCgroup.compile(rules)
              program = load(instructions, license, resource_id: "bpf:device-filter:load")
              @programs[key] = program
              @programs.shift.last.close while @programs.length > @cache_limit
              program
            end
          end

          def load(instructions, license, resource_id:)
            bpf.load(instructions: instructions, program_type: BPF::BPF_PROG_TYPE_CGROUP_DEVICE, license: license,
                     expected_attach_type: BPF::BPF_CGROUP_DEVICE, name: NAME, resource_id: resource_id)
          end

          def with_cgroup(path)
            raise Error, "cgroup path must be absolute" unless path.start_with?("/")

            # Ruby opens descriptors close-on-exec.
            File.open(path, File::RDONLY | O_DIRECTORY) { |directory| yield directory }
          end
        end
      end
    end
  end
end
