#!/usr/bin/env ruby
# frozen_string_literal: true

# Writes lib/rubernetes/api/table_printer/columns.rb: the column definitions
# every table handler registers in pkg/printers/internalversion AddHandlers
# (Kubernetes v1.36.2), keyed by kind, dumped by the printers oracle so the
# Swagger-derived descriptions are exactly upstream's.
#
#   ruby tools/schema/import_table_columns.rb

require_relative "../differential/printers_oracle"

entries = PrintersOracle.run("mode" => "columns").reject { |entry| entry["type"].end_with?("List") }
duplicates = entries.group_by { |entry| entry["type"] }.select { |_, group| group.length > 1 }.keys
raise "kinds registered twice: #{duplicates.join(", ")}" unless duplicates.empty?

pod = entries.find { |entry| entry["type"] == "Pod" }.fetch("columns")
lines = []
lines << "# frozen_string_literal: true"
lines << ""
lines << "# GENERATED by tools/schema/import_table_columns.rb from"
lines << "# pkg/printers/internalversion AddHandlers (Kubernetes v1.36.2).  Do not edit."
lines << ""
lines << "module Rubernetes"
lines << "  module API"
lines << "    module TablePrinter"
lines << "      NAME_DESCRIPTION = #{pod[0].fetch("description").inspect}"
lines << "      CREATION_TIMESTAMP_DESCRIPTION = #{pod[4].fetch("description").inspect}"
lines << ""
lines << "      COLUMNS = {"
entries.each do |entry|
  lines << "        #{entry["type"].inspect} => [ # #{entry["package"]}"
  entry["columns"].each do |column|
    fields = %w[name type format description priority].map { |key| "#{key.inspect} => #{column.fetch(key).inspect}" }
    lines << "          {#{fields.join(", ")}}.freeze,"
  end
  lines << "        ].freeze,"
end
lines << "      }.freeze"
lines << "    end"
lines << "  end"
lines << "end"
path = File.join(PrintersOracle::ROOT, "lib/rubernetes/api/table_printer/columns.rb")
File.write(path, lines.join("\n") << "\n")
puts "wrote #{entries.length} kinds to #{path}"
