# frozen_string_literal: true

require "digest"
require "etc"
require "ipaddr"
require "socket"
require "thread"

require_relative "../platform/linux/bpf"
require_relative "ebpf_program"

module Rubernetes
  module Proxy
    # A Linux TC adapter for the proxy's kernel resources. The adapter owns
    # only kernel mechanics: map creation/update, binary program loading, and
    # TC filter attachment/readback. The instruction stream is generated by
    # EBPFProgram::ServiceDatapath so the same Ruby wire format drives both
    # map synchronization and the verifier-visible packet path.
    class LinuxEBPFAdapter
      BPF = Rubernetes::Platform::Linux::BPF

      AF_UNSPEC = 0
      NETLINK_ROUTE = 0
      NLM_F_REQUEST = 0x01
      NLM_F_MULTI = 0x02
      NLM_F_ACK = 0x04
      NLM_F_EXCL = 0x200
      NLM_F_REPLACE = 0x100
      NLM_F_CREATE = 0x400
      NLM_F_DUMP = NLM_F_REQUEST | 0x300
      NLMSG_ERROR = 0x02
      NLMSG_DONE = 0x03
      RTM_NEWQDISC = 36
      RTM_DELQDISC = 37
      RTM_NEWTFILTER = 44
      RTM_DELTFILTER = 45
      RTM_GETTFILTER = 46
      NLMSG_HEADER_SIZE = 16
      TCMSG_SIZE = 20

      TC_H_ROOT = 0xffff_ffff
      TC_H_CLSACT = 0xffff_fff1
      TC_H_MIN_INGRESS = 0xfff2
      TC_H_MIN_EGRESS = 0xfff3
      TC_PARENT_INGRESS = 0xffff_fff2
      TC_PARENT_EGRESS = 0xffff_fff3
      ETH_P_ALL = 0x0003
      # tcm_info stores the filter priority in the high half and the
      # protocol in network byte order in the low half (TC_H_MAKE). Keep the
      # wire representation explicit; putting these halves in the opposite
      # order creates a perfectly readable filter that never matches packets.
      ETH_P_ALL_NETWORK = [ETH_P_ALL].pack("n").unpack1("S<")

      TCA_KIND = 1
      TCA_OPTIONS = 2
      TCA_BPF_FD = 6
      TCA_BPF_NAME = 7
      TCA_BPF_FLAGS = 8
      TCA_BPF_ID = 11
      TCA_BPF_FLAG_ACT_DIRECT = 1

      DEFAULT_PROGRAM_NAME = "rkproxy_tc"
      DEFAULT_PRIORITY = 32_700
      DEFAULT_HANDLE = 0x7e00
      PROTOCOLS = {"TCP" => 6, "UDP" => 17, "SCTP" => 132}.freeze
      MAP_LAYOUT = {
        "service_rules" => {"type" => "hash", "key_size" => 40,
                             "value_size" => EBPFProgram::WireFormat::SERVICE_VALUE_SIZE, "max_entries" => 65_536},
        "backends" => {"type" => "array_of_structs", "key_size" => EBPFProgram::WireFormat::BACKEND_KEY_SIZE,
                       "value_size" => EBPFProgram::WireFormat::BACKEND_VALUE_SIZE, "max_entries" => 1_000_000},
        "conntrack" => {"type" => "lru_hash", "key_size" => EBPFProgram::WireFormat::CONNTRACK_KEY_SIZE,
                        "value_size" => EBPFProgram::WireFormat::CONNTRACK_VALUE_SIZE, "max_entries" => 1_000_000},
        "client_ip_affinity" => {"type" => "lru_hash", "key_size" => EBPFProgram::WireFormat::AFFINITY_KEY_SIZE,
                                 "value_size" => EBPFProgram::WireFormat::AFFINITY_VALUE_SIZE, "max_entries" => 1_000_000},
        "source_ranges" => {"type" => "lpm_trie", "key_size" => EBPFProgram::WireFormat::SOURCE_RANGE_KEY_SIZE,
                             "value_size" => EBPFProgram::WireFormat::SOURCE_RANGE_VALUE_SIZE, "max_entries" => 65_536},
        "sctp_crc32c" => {"type" => "array", "key_size" => 4,
                           "value_size" => 4, "max_entries" => 256},
        "snat" => {"type" => "lru_hash", "key_size" => EBPFProgram::WireFormat::SNAT_KEY_SIZE,
                   "value_size" => EBPFProgram::WireFormat::SNAT_VALUE_SIZE, "max_entries" => 1_000_000}
      }.freeze

      class TCNetlink
        Message = Data.define(:type, :flags, :sequence, :payload)

        def initialize(socket_factory: nil, timeout: 2.0)
          @socket_factory = socket_factory || method(:open_socket)
          @timeout = Float(timeout)
          raise ArgumentError, "netlink timeout must be positive" unless @timeout.positive?

          @mutex = Mutex.new
          @sequence = 0
        end

        def request(type:, flags:, payload:, attributes: [], resource_id: "proxy:tc")
          sequence = next_sequence
          body = String(payload).b << attributes.join
          message = [NLMSG_HEADER_SIZE + body.bytesize, Integer(type), Integer(flags), sequence, 0]
                    .pack("L<S<S<L<L<") << body
          socket = @socket_factory.call
          socket.bind([Socket::AF_NETLINK, 0, 0, 0].pack("S<S<L<L<")) if socket.respond_to?(:bind)
          sent = socket.send(message, 0)
          raise IOError, "rtnetlink request was short-written" unless sent == message.bytesize

          receive(socket, sequence: sequence, resource_id: resource_id)
        rescue Rubernetes::Platform::Linux::Error
          raise
        rescue SystemCallError => error
          raise Rubernetes::Platform::Linux::Error.wrap(error, operation: "rtnetlink", resource_id: resource_id), cause: error
        ensure
          socket&.close
        end

        def self.attribute(type, value, nested: false)
          body = String(value).b
          attribute_type = Integer(type)
          attribute_type |= 0x8000 if nested
          length = 4 + body.bytesize
          [length, attribute_type].pack("S<S<") << body << ("\0" * (align(length) - length))
        end

        def self.align(length)
          (Integer(length) + 3) & ~3
        end

        private

        def open_socket
          Socket.new(Socket::AF_NETLINK, Socket::SOCK_RAW, NETLINK_ROUTE)
        end

        def next_sequence
          @mutex.synchronize do
            @sequence = (@sequence + 1) & 0xffff_ffff
            @sequence = 1 if @sequence.zero?
            @sequence
          end
        end

        def receive(socket, sequence:, resource_id:)
          deadline = Process.clock_gettime(Process::CLOCK_MONOTONIC) + @timeout
          messages = []
          loop do
            remaining = deadline - Process.clock_gettime(Process::CLOCK_MONOTONIC)
            if remaining <= 0 || IO.select([socket], nil, nil, remaining).nil?
              raise Rubernetes::Platform::Linux::Error.new(
                errno: Errno::ETIMEDOUT::Errno, operation: "rtnetlink_ack", resource_id: resource_id
              )
            end

            parse(socket.recv(65_536)).each do |message|
              next unless message.sequence == sequence

              if message.type == NLMSG_ERROR
                error_code = message.payload.bytesize >= 4 ? message.payload.unpack1("l<") : -Errno::EPROTO::Errno
                unless error_code.zero?
                  raise Rubernetes::Platform::Linux::Error.new(
                    errno: error_code.abs, operation: "rtnetlink_ack", resource_id: resource_id
                  )
                end
                return messages.freeze
              end
              messages << message
              return messages.freeze if message.type == NLMSG_DONE
            end
          end
        end

        def parse(buffer)
          bytes = String(buffer).b
          messages = []
          offset = 0
          while offset + NLMSG_HEADER_SIZE <= bytes.bytesize
            length, type, flags, sequence, = bytes.byteslice(offset, NLMSG_HEADER_SIZE).unpack("L<S<S<L<L<")
            raise IOError, "rtnetlink response has invalid length" if length < NLMSG_HEADER_SIZE || offset + length > bytes.bytesize

            payload = bytes.byteslice(offset + NLMSG_HEADER_SIZE, length - NLMSG_HEADER_SIZE)
            messages << Message.new(type: type, flags: flags, sequence: sequence, payload: payload.freeze)
            offset += self.class.align(length)
          end
          raise IOError, "rtnetlink response is truncated" unless offset == bytes.bytesize

          messages
        end
      end

      attr_reader :bpf, :netlink, :maps, :program, :links

      # The SCTP CRC32c rewrite is the only Service datapath feature whose
      # support boundary is expressed as a kernel release: the spec pins the
      # bpf_loop static-callback path to Linux >= 6.12.  Every other feature
      # (TCP/UDP DNAT, reverse SNAT, conntrack, affinity, TC attach) is
      # proven by the verifier and packet readback on the running kernel.
      SCTP_CRC32C_MINIMUM_RELEASE = [6, 12].freeze
      SCTP_CRC32C_WAIVER_REQUIREMENT = "linux>=6.12"
      SCTP_CRC32C_WAIVER_SCOPE = "sctp-crc32c-ebpf"
      KERNEL_WAIVER_ENV = "RUBERNETES_M4_KERNEL_WAIVER_REASON"

      def initialize(bpf: BPF.new, netlink: TCNetlink.new, interface: nil, ifindex: nil,
                     complete_semantics: false, semantic_probe: nil,
                     program_name: DEFAULT_PROGRAM_NAME, map_layout: nil, kernel_release: nil,
                     helper_attestation: nil, kernel_waiver: ENV[KERNEL_WAIVER_ENV])
        @bpf = bpf
        @netlink = netlink
        @interface = interface
        @ifindex = ifindex
        @complete_semantics = !!complete_semantics
        @semantic_probe = semantic_probe
        raise ArgumentError, "semantic_probe must respond to call" if @semantic_probe && !@semantic_probe.respond_to?(:call)
        @program_name = normalize_name(program_name)
        @map_layout = deep_freeze(map_layout || default_map_layout)
        # The uname release is the only release that may authorize a
        # production datapath.  A release override remains accepted for
        # deterministic unit vectors, but it permanently marks this adapter
        # non-production so a fixture cannot impersonate the host kernel.
        @actual_kernel_release = String(Etc.uname.fetch(:release)).freeze
        @kernel_release_override = kernel_release&.to_s&.freeze
        @kernel_release = @actual_kernel_release
        # An operator waiver of the release requirement is recorded, never
        # inferred: it names the waived requirement, its scope, the reason,
        # and the host kernel so evidence consumers can see exactly what was
        # relaxed.  It applies only to the real host release; a fixture
        # override describes a hypothetical kernel and is never waived.
        @kernel_waiver = normalize_kernel_waiver(kernel_waiver)
        @mutex = Mutex.new
        @maps = {}.freeze
        @program = nil
        @links = [].freeze
        @attached = false
        @service_keys = {}.freeze
        @backend_keys = {}.freeze
        @source_range_keys = {}.freeze
        @crc32c_initialized = false
        @semantic_verified = false
        @semantic_evidence = nil
        @semantic_evidence_attested = false
        @verifier_attested = false
        @helper_attested = false
        # An external helper report can be retained for diagnostics, but it
        # can never authorize a production identity.  This flag is set only
        # after a fresh BPF_OBJ_GET_INFO_BY_FD readback for @program.
        @helper_live_readback_attested = false
        @helper_attestation = helper_attestation
        @tc_attach_attested = false
        @attached_program_spec = nil
        @inlinable_array_lookups = 0
        @loaded_instructions = nil
      end

      attr_reader :semantic_evidence

      attr_reader :kernel_release

      attr_reader :actual_kernel_release

      def kernel_release_override
        @kernel_release_override
      end

      attr_reader :kernel_waiver

      def production_release_attested?
        @kernel_release_override.nil? && sctp_crc32c_kernel_supported?(release: @actual_kernel_release)
      end

      # True when the SCTP CRC32c requirement is satisfied by the release
      # itself, without a waiver.
      def sctp_crc32c_release_supported?(release: nil)
        release = @kernel_release_override || release || @actual_kernel_release
        version = release.to_s.split(/[.-]/, 3).first(2).map(&:to_i)
        major = version.fetch(0, 0)
        minor = version.fetch(1, 0)
        ([major, minor] <=> SCTP_CRC32C_MINIMUM_RELEASE) >= 0
      end

      def sctp_crc32c_waived?
        !@kernel_waiver.nil? && @kernel_release_override.nil? && !sctp_crc32c_release_supported?(release: @actual_kernel_release)
      end

      # After a load, the kernel's own translated-program readback tells
      # whether the bpf_loop static callback was accepted: helper 181 must
      # appear among the translated calls and the func_info must describe
      # more than the entry function.  A release string cannot prove this.
      def sctp_crc32c_live_attested?
        program = @program
        return false unless program.respond_to?(:translated_helper_calls) && program.respond_to?(:load_evidence)

        evidence = program.load_evidence
        Array(program.requested_helper_calls).include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP) &&
          helper_call_counts_consistent?(program.requested_helper_calls, program.translated_helper_calls) &&
          evidence.is_a?(Hash) && evidence["func_info_count"].to_i >= 2
      rescue StandardError
        false
      end

      def sctp_crc32c_status
        {
          "minimumRelease" => SCTP_CRC32C_MINIMUM_RELEASE.join("."),
          "hostKernel" => @actual_kernel_release,
          "releaseSupported" => sctp_crc32c_release_supported?(release: @actual_kernel_release),
          "waived" => sctp_crc32c_waived?,
          "waiver" => @kernel_waiver,
          "liveBpfLoopAttested" => sctp_crc32c_live_attested?
        }.freeze
      end

      SEMANTIC_PROOF_CASES = %w[
        ipv4_tcp_cluster_ip ipv4_udp_cluster_ip ipv4_sctp_cluster_ip
        ipv6_tcp_cluster_ip ipv6_udp_cluster_ip ipv6_sctp_cluster_ip
        ipv4_tcp_node_port ipv4_udp_node_port ipv4_sctp_node_port
        ipv6_tcp_node_port ipv6_udp_node_port ipv6_sctp_node_port
        ipv4_tcp_external_ip ipv4_udp_external_ip ipv4_sctp_external_ip
        ipv6_tcp_external_ip ipv6_udp_external_ip ipv6_sctp_external_ip
        ipv4_tcp_load_balancer ipv4_udp_load_balancer ipv4_sctp_load_balancer
        ipv6_tcp_load_balancer ipv6_udp_load_balancer ipv6_sctp_load_balancer
        ipv4_tcp_headless ipv4_udp_headless ipv4_sctp_headless
        ipv6_tcp_headless ipv6_udp_headless ipv6_sctp_headless
        external_name_cname
        ipv4_distinct_address_reverse ipv6_distinct_address_reverse
        health_check_node_port ipv4_fragments ipv6_fragments
        session_affinity_client_ip internal_traffic_policy_local external_traffic_policy_local
        terminating_endpoints dual_stack_service
      ].freeze

      # Ask the kernel verifier whether the complete Service datapath is
      # accepted for SCHED_CLS on this host.  Maps are created exactly as
      # attach would create them (the program embeds their descriptors), the
      # program is loaded once, its identity is read back, and everything is
      # closed again; nothing is attached to any device.  The result is the
      # evidence AutoBackend records for its selection.
      def verifier_probe(map_layout: @map_layout)
        maps = {}
        program = nil
        started = Process.clock_gettime(Process::CLOCK_MONOTONIC)
        specs = normalize_map_layout(map_layout)
        specs.each { |name, spec| maps[name] = create_map(name, spec, ifindex: 0) }
        instructions = compile_program(maps: maps)
        program = @bpf.load(
          instructions: instructions,
          program_type: BPF::BPF_PROG_TYPE_SCHED_CLS,
          log_size: BPF::MAX_LOG_SIZE,
          expected_attach_type: 0,
          ifindex: 0,
          name: @program_name,
          map_fds: maps.values.map(&:fd),
          resource_id: "proxy:ebpf:verifier-probe"
        )
        {
          "accepted" => true,
          "kernelRelease" => @actual_kernel_release,
          "programType" => "BPF_PROG_TYPE_SCHED_CLS",
          "programId" => program.id,
          "programTag" => program.tag,
          "instructionCount" => instructions.length,
          "xlatedInstructionCount" => program.xlated_instructions.length,
          "verifiedInsns" => program.verified_insns,
          "verifierLog" => program.verifier_log,
          "verifierLogSha256" => program.verifier_log_sha256,
          "loadEvidenceSha256" => program.load_evidence_sha256,
          "requestedHelperIds" => program.requested_helper_ids,
          "translatedHelperCallCount" => program.translated_helper_calls.length,
          "requestedHelperCallCount" => program.requested_helper_calls.length,
          "sctpCrc32c" => sctp_crc32c_status.merge(
            "liveBpfLoopAttested" => Array(program.requested_helper_calls).include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP) &&
                                     program.load_evidence.is_a?(Hash) && program.load_evidence["func_info_count"].to_i >= 2
          ),
          "mapIds" => maps.transform_values(&:id),
          "durationMs" => ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started) * 1000.0).round(3)
        }.freeze
      rescue BPF::VerifierError => error
        {
          "accepted" => false,
          "kernelRelease" => @actual_kernel_release,
          "programType" => "BPF_PROG_TYPE_SCHED_CLS",
          "errno" => error.errno,
          "error" => error.message,
          "verifierLog" => error.verifier_log,
          "verifierLogSha256" => Digest::SHA256.hexdigest(error.verifier_log.to_s),
          "instructionCount" => instructions&.length
        }.freeze
      rescue ArgumentError, Rubernetes::Platform::Linux::Error, SystemCallError, IOError, RuntimeError => error
        {"accepted" => false, "kernelRelease" => @actual_kernel_release, "error" => "#{error.class}: #{error.message}"}.freeze
      ensure
        program&.close
        maps.each_value { |map| map.close rescue nil }
      end

      # Production selection is deliberately gated by both the explicit
      # production opt-in and an isolated packet/readback proof supplied by
      # the caller. A verifier-accepted program alone is not a Service proxy.
      def production_capable?
        @complete_semantics && @semantic_verified && service_semantics_complete? &&
          production_release_attested? && @verifier_attested && @helper_attested && @helper_live_readback_attested &&
          @tc_attach_attested && @semantic_evidence_attested
      end

      def service_semantics_complete?
        required = %i[ipv4 ipv6 tcp udp sctp_ports deterministic_backend_selection conntrack
                      client_ip_affinity dnat reverse_snat checksum_recompute sctp_crc32c
                      forward_masquerade ipv6_extension_headers fragment_drop vlan_encapsulation
                      topology_hints load_balancer_source_ranges health_check_node_port]
        required.all? { |feature| EBPFProgram::ServiceDatapath::FEATURE_MATRIX.fetch(feature) } &&
          sctp_crc32c_kernel_supported?
      end

      def sctp_crc32c_kernel_supported?(release: nil)
        return true if sctp_crc32c_release_supported?(release: release)

        # Only the real host release can be waived, and only for the SCTP
        # CRC32c scope; the waiver is surfaced through kernel_identity and
        # production_capability_error so it is never a silent skip.
        effective = @kernel_release_override || release || @actual_kernel_release
        @kernel_release_override.nil? && effective == @actual_kernel_release && !@kernel_waiver.nil?
      end

      def unimplemented_semantics
        EBPFProgram::ServiceDatapath::FEATURE_MATRIX.each_with_object([]) do |(feature, supported), result|
          result << feature.to_s unless supported
        end.freeze
      end

      def production_capability_error
        gaps = unimplemented_semantics.dup
        gaps << "semantic_packet_proof" unless @semantic_verified
        gaps << "complete_semantics_opt_in" unless @complete_semantics
        gaps << "actual_kernel_release" unless production_release_attested?
        gaps << "verifier_program_readback" unless @verifier_attested
        gaps << "helper_readback" unless @helper_attested
        gaps << "live_helper_readback" unless @helper_live_readback_attested
        gaps << "tc_filter_readback" unless @tc_attach_attested
        gaps << "external_packet_evidence" unless @semantic_evidence_attested
        return "eBPF adapter is production-capable" if gaps.empty?

        detail = []
        detail << "M4 eBPF gate requires Linux >= 6.12 for SCTP CRC32c (observed #{@actual_kernel_release}); set #{KERNEL_WAIVER_ENV} to record an explicit waiver" unless production_release_attested?
        detail << "SCTP CRC32c release requirement waived: #{@kernel_waiver.fetch("reason")}" if sctp_crc32c_waived?
        detail << "SCTP CRC32c requires a verified bpf_loop static callback and BPF_PSEUDO_FUNC relocation" if gaps.include?("sctp_crc32c")
        detail << "kernel verifier/load evidence is not content-bound" unless @verifier_attested
        detail << "live kernel helper ID readback is incomplete; external helper attestation is test-only" unless @helper_live_readback_attested
        detail << "TC filter identity readback is incomplete" unless @tc_attach_attested
        detail << "kernel_release override is test-only and cannot authorize production" if @kernel_release_override
        detail << "TC cannot reassemble IPv4 fragments; both datapaths use explicit fail-closed fragment handling" if gaps.include?("ipv4_fragment_reassembly")
        "eBPF adapter is not production-capable: #{(detail + gaps).join('; ')}"
      end

      # The evidence is intentionally explicit: the kernel cannot tell this
      # adapter that a real packet crossed a veth. Callers must provide the
      # isolated test readback after checking both directions and checksums.
      def verify_packet_semantics!(evidence:)
        evidence = evidence.transform_keys(&:to_sym) if evidence.respond_to?(:transform_keys)
        required = %i[readback forward_dnat reverse_snat checksum_recompute]
        missing = required.reject { |key| evidence.is_a?(Hash) && evidence[key] == true }
        matrix = evidence.is_a?(Hash) ? (evidence[:matrix] || evidence["matrix"]) : nil
        missing_cases = SEMANTIC_PROOF_CASES.reject { |key| matrix.is_a?(Hash) && matrix[key] == true }
        missing << "matrix:#{missing_cases.join(',')}" unless missing_cases.empty?
        raise ArgumentError, "packet semantics evidence is incomplete: #{missing.join(', ')}" unless missing.empty?

        @mutex.synchronize do
          raise RuntimeError, "eBPF adapter must be attached before packet proof" unless @attached

          @semantic_evidence = evidence.freeze
          @semantic_verified = true
          @semantic_evidence_attested = semantic_evidence_attested?(evidence)
        end
        true
      end

      def mechanically_capable?
        true
      end

      # Return only identities observed from the live kernel, with helper
      # evidence bound to the accepted load. An external helper attestation is
      # accepted only when it names this program and its content-bound load
      # evidence digest.
      def kernel_identity
        return nil unless @verifier_attested && @helper_attested && @tc_attach_attested && @program
        return nil unless helper_attestation_matches_program?

        {
          "kernelRelease" => @actual_kernel_release,
          "sctpCrc32c" => sctp_crc32c_status,
          "kernelWaiver" => @kernel_waiver,
          "program" => {
            "id" => @program.id,
            "name" => @program.name,
            "tag" => @program.tag,
            "type" => @program.type,
            "helperIds" => observed_helper_ids,
            "requestedHelperIds" => program_requested_helper_ids(@program),
            "requestedHelperCalls" => program_requested_helper_calls(@program),
            "verifierLogSha256" => @program.verifier_log_sha256,
            "loadEvidenceSha256" => @program.load_evidence_sha256,
            "xlatedProgramSha256" => @program.xlated_program_sha256,
            "verifiedInsns" => @program.verified_insns
          },
          "helperIds" => observed_helper_ids,
          "requestedHelperIds" => program_requested_helper_ids(@program),
          "requestedHelperCalls" => program_requested_helper_calls(@program),
          "helperObservationSource" => helper_observation_source,
          "verifierLogSha256" => @program.verifier_log_sha256,
          "loadEvidenceSha256" => @program.load_evidence_sha256,
          "helperEvidence" => @helper_attestation,
          "maps" => @maps.map do |name, map|
            info = @bpf.map_info(map, resource_id: "proxy:ebpf:map:#{name}:identity")
            info.slice(:id, :name, :type, :key_size, :value_size, :max_entries, :flags)
          end,
          "filters" => @links.map do |link|
            link.slice(:ifindex, :direction, :handle, :parent, :priority).merge("programId" => link[:program_id] || @program.id)
          end
        }.freeze
      rescue StandardError
        nil
      end

      def attach(hook: :tc, backend: nil, map_layout: @map_layout, interface: @interface,
                 ifindex: @ifindex, program: nil, helper_attestation: nil, **_options)
        @mutex.synchronize do
          raise RuntimeError, "eBPF adapter is already attached" if @attached

          target_ifindices = resolve_ifindices(interface: interface, ifindex: ifindex)
          target_ifindex = target_ifindices.first
          directions = normalize_hooks(hook)
          maps = {}
          loaded_program = nil
          attached_links = []
          begin
            @attached_program_spec = deep_freeze(program) if program
            ensure_sctp_crc32c_kernel!(layout: map_layout)
            specs = normalize_map_layout(map_layout)
            specs.each do |name, spec|
              maps[name] = create_map(name, spec, ifindex: target_ifindex)
            end
            sync_maps(maps, Array(backend&.rules))
            instructions = compile_program(maps: maps)
            @inlinable_array_lookups = count_inlinable_array_lookups(instructions, maps)
            @loaded_instructions = instructions
            loaded_program = @bpf.load(
              instructions: instructions,
              program_type: BPF::BPF_PROG_TYPE_SCHED_CLS,
              # Extension-header and policy branches can produce a verifier
              # trace larger than the small diagnostic default; preserve the
              # complete kernel reason instead of surfacing a bare ENOSPC.
              log_size: BPF::MAX_LOG_SIZE,
              expected_attach_type: 0,
              # prog_ifindex is for device-offloaded programs; software TC
              # classifiers are associated with the netdev by rtnetlink.
              ifindex: 0,
              name: @program_name,
              map_fds: maps.values.map(&:fd),
              resource_id: "proxy:ebpf:program"
            )
            # A Service datapath must see both the client-facing veth (DNAT
            # on ingress, reverse SNAT on egress) and every backend-facing
            # veth (un-masquerade on ingress); one program serves all of
            # them, so the same FD is attached per device and direction.
            # Masqueraded flows re-enter the IPv4 stack from TC ingress with
            # the node's own address as source; without accept_local the
            # router discards them as martian.  The previous values are kept
            # so detach restores the host configuration.
            configure_accept_local!(target_ifindices)
            target_ifindices.each do |device_ifindex|
              directions.each do |direction|
                ensure_clsact(device_ifindex)
                attached_links << attach_filter(device_ifindex, direction, loaded_program)
              end
            end
            @maps = maps.freeze
            @program = loaded_program
            @links = attached_links.freeze
            @service_keys = current_service_keys(Array(backend&.rules)).freeze
            @backend_keys = current_backend_keys(Array(backend&.rules)).freeze
            @source_range_keys = current_source_range_keys(Array(backend&.rules)).freeze
            readback = verify_kernel_state(target_ifindex)
            @verifier_attested = load_evidence_attested?(loaded_program, readback)
            @helper_attestation = helper_attestation_for(loaded_program, helper_attestation || @helper_attestation)
            @helper_attested = !@helper_attestation.nil?
            @tc_attach_attested = tc_attach_readback_attested?(readback)
            unless @verifier_attested && @helper_attested && @tc_attach_attested
              raise RuntimeError, production_capability_error
            end
            @attached = true
            run_semantic_probe if @semantic_probe
            result_for(readback)
          rescue StandardError
            attached_links.each { |link| delete_filter(link.fetch(:ifindex), link) rescue nil }
            loaded_program&.close rescue nil
            maps.each_value { |map| map.close rescue nil }
            @program = nil
            @maps = {}.freeze
            @links = [].freeze
            @attached = false
            @crc32c_initialized = false
            @semantic_verified = false
            @semantic_evidence = nil
            @semantic_evidence_attested = false
            @verifier_attested = false
            @helper_attested = false
            @helper_live_readback_attested = false
            @helper_attestation = nil
            @tc_attach_attested = false
            @attached_program_spec = nil
            @loaded_instructions = nil
            raise
          end
        end
      end

      def verify_attach(result:, expected:, backend:, **_context)
        return false unless result.is_a?(Hash) && result[:verified] == true

        target_ifindex = result.dig(:interface, :ifindex) || result.dig("interface", "ifindex")
        return false unless target_ifindex

        @mutex.synchronize do
          return false unless @attached && @program && @program.id

          readback = verify_kernel_state(Integer(target_ifindex))
          identity_matches?(result, readback) && expected_program_matches?(expected)
        end
      rescue StandardError
        false
      end

      def update(backend:, diff:, program: nil, **_options)
        @mutex.synchronize do
          raise RuntimeError, "eBPF adapter is not attached" unless @attached

          rules = Array(backend.rules)
          sync_maps(@maps, rules)
          @service_keys = current_service_keys(rules).freeze
          @backend_keys = current_backend_keys(rules).freeze
          @source_range_keys = current_source_range_keys(rules).freeze
          readback = verify_kernel_state(@links.first.fetch(:ifindex))
          result_for(readback).merge(diff: diff, program_id: @program.id).freeze
        end
      end

      alias apply_diff update

      def verify_update(result:, backend:, **_context)
        return false unless result.is_a?(Hash) && result[:verified] == true

        @mutex.synchronize do
          next false unless @attached && @program

          readback = verify_kernel_state(@links.first.fetch(:ifindex))
          result[:program_id].to_i == @program.id && identity_matches?(result, readback)
        end
      rescue StandardError
        false
      end

      def detach(**_options)
        @mutex.synchronize do
          return true unless @attached || @program || !@maps.empty?

          errors = []
          Array(@links).each do |link|
            begin
              delete_filter(link.fetch(:ifindex), link)
            rescue StandardError => error
              errors << error
            end
          end
          begin
            @program&.close
          rescue StandardError => error
            errors << error
          end
          @maps.each_value do |map|
            begin
              map.close
            rescue StandardError => error
              errors << error
            end
          end
          begin
            restore_accept_local!
          rescue StandardError => error
            errors << error
          end
          @program = nil
          @maps = {}.freeze
          @links = [].freeze
          @attached = false
          @service_keys = {}.freeze
          @backend_keys = {}.freeze
          @source_range_keys = {}.freeze
          @crc32c_initialized = false
          @semantic_verified = false
          @semantic_evidence = nil
          @semantic_evidence_attested = false
          @verifier_attested = false
          @helper_attested = false
          @helper_live_readback_attested = false
          @helper_attestation = nil
          @tc_attach_attested = false
          @attached_program_spec = nil
          @loaded_instructions = nil
          raise errors.first unless errors.empty?

          true
        end
      end

      # Generate the verifier-visible Service datapath. Map descriptors are
      # embedded as BPF pseudo-map-FD instructions after map creation, so a
      # program loaded for one adapter cannot accidentally reference another
      # adapter's maps.
      def compile_program(maps: @maps)
        normalized_maps = Array(maps).each_with_object({}) do |entry, result|
          name, map = entry
          result[name.to_s] = map.fd
        end
        EBPFProgram::ServiceDatapath.new(map_fds: normalized_maps).build
      end

      private

      def ensure_sctp_crc32c_kernel!(layout: @map_layout)
        names = layout.respond_to?(:keys) ? layout.keys.map(&:to_s) : []
        raise ArgumentError, "sctp_crc32c map is mandatory for every eBPF proxy layout" unless names.include?("sctp_crc32c")
        return true if sctp_crc32c_kernel_supported?

        raise RuntimeError, "M4 eBPF gate requires Linux >= 6.12 for SCTP CRC32c (observed #{@kernel_release}); " \
                            "set #{KERNEL_WAIVER_ENV} to record an explicit waiver"
      end

      def normalize_kernel_waiver(value)
        return nil if value.nil?

        reason = value.is_a?(Hash) ? (value["reason"] || value[:reason]) : value
        reason = String(reason).strip
        return nil if reason.empty?

        {
          "requirement" => SCTP_CRC32C_WAIVER_REQUIREMENT,
          "scope" => SCTP_CRC32C_WAIVER_SCOPE,
          "reason" => reason,
          "host_kernel" => @actual_kernel_release,
          "waived_at" => Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%6NZ")
        }.freeze
      end

      def default_map_layout
        if defined?(EBPFBackend) && EBPFBackend.const_defined?(:MAP_LAYOUT, false)
          EBPFBackend::MAP_LAYOUT
        else
          MAP_LAYOUT
        end
      end

      def run_semantic_probe
        evidence = @semantic_probe.call(self)
        evidence = evidence.transform_keys(&:to_sym) if evidence.respond_to?(:transform_keys)
        required = %i[readback forward_dnat reverse_snat checksum_recompute]
        missing = required.reject { |key| evidence.is_a?(Hash) && evidence[key] == true }
        matrix = evidence.is_a?(Hash) ? (evidence[:matrix] || evidence["matrix"]) : nil
        missing_cases = SEMANTIC_PROOF_CASES.reject { |key| matrix.is_a?(Hash) && matrix[key] == true }
        missing << "matrix:#{missing_cases.join(',')}" unless missing_cases.empty?
        raise ArgumentError, "packet semantics evidence is incomplete: #{missing.join(', ')}" unless missing.empty?

        @semantic_evidence = evidence.freeze
        @semantic_verified = true
        @semantic_evidence_attested = semantic_evidence_attested?(evidence)
      rescue StandardError => error
        @semantic_verified = false
        @semantic_evidence = nil
        @semantic_evidence_attested = false
        raise RuntimeError, "eBPF packet semantics probe failed: #{error.message}"
      end

      def semantic_evidence_attested?(evidence)
        return false unless evidence.is_a?(Hash)

        source = evidence[:measurement_source] || evidence["measurement_source"] || evidence[:measurementSource] || evidence["measurementSource"]
        trace = evidence[:packet_trace_sha256] || evidence["packet_trace_sha256"] || evidence[:packetTraceSha256] || evidence["packetTraceSha256"]
        count = evidence[:packet_count] || evidence["packet_count"] || evidence[:packetCount] || evidence["packetCount"]
        kernel = evidence[:kernel] || evidence["kernel"] || evidence[:kernel_identity] || evidence["kernelIdentity"]
        return false unless source.to_s != "" && source.to_s != "model_only" && trace.to_s.match?(/\A[0-9a-f]{64}\z/i) && count.to_i.positive?
        return false unless kernel.is_a?(Hash) && (kernel[:release] || kernel["release"] || kernel[:kernelRelease] || kernel["kernelRelease"]).to_s == @actual_kernel_release

        program_id = kernel[:program_id] || kernel["program_id"] || kernel[:programId] || kernel["programId"]
        filter_ids = kernel[:filter_program_ids] || kernel["filter_program_ids"] || kernel[:filterProgramIds] || kernel["filterProgramIds"]
        helpers = kernel[:helper_ids] || kernel["helper_ids"] || kernel[:helperIds] || kernel["helperIds"]
        requested_helpers = kernel[:requested_helper_ids] || kernel["requested_helper_ids"] ||
          kernel[:requestedHelperIds] || kernel["requestedHelperIds"]
        program_id.to_i == @program&.id && Array(filter_ids).map(&:to_i).include?(@program&.id) &&
          (Array(helpers).map(&:to_i).include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP) ||
           Array(requested_helpers).map(&:to_i).include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP))
      end

      def observed_helper_ids
        return [].freeze unless @program&.respond_to?(:helper_ids)

        Array(@program.helper_ids).map(&:to_i).uniq.sort.freeze
      end

      def program_requested_helper_ids(program)
        return [].freeze unless program.respond_to?(:requested_helper_ids)

        Array(program.requested_helper_ids).map(&:to_i).uniq.sort.freeze
      end

      def program_requested_helper_calls(program)
        return [].freeze unless program.respond_to?(:requested_helper_calls)

        Array(program.requested_helper_calls).map(&:to_i).freeze
      end

      def program_translated_helper_calls(program)
        return [].freeze unless program.respond_to?(:translated_helper_calls)

        Array(program.translated_helper_calls).map(&:to_i).freeze
      end

      def program_helper_ids(program)
        return [].freeze unless program.respond_to?(:helper_ids)

        Array(program.helper_ids).map(&:to_i).uniq.sort.freeze
      end

      def helper_ids_from_hash(document)
        return nil unless document.is_a?(Hash)

        key = %i[helper_ids helperIds].find { |candidate| document.key?(candidate) } ||
          %w[helper_ids helperIds].find { |candidate| document.key?(candidate) }
        return nil unless key

        value = document.fetch(key)
        return nil if value.nil?

        Array(value).map(&:to_i).uniq.sort.freeze
      rescue StandardError
        nil
      end

      def helper_attestation_helper_ids(attestation)
        helper_ids_from_hash(attestation)
      end

      def helper_attestation_matches_program?
        return false unless @program && @helper_attestation.is_a?(Hash)

        helper_ids = helper_attestation_helper_ids(@helper_attestation)
        !helper_ids.nil? && helper_ids == program_helper_ids(@program)
      end

      def helper_observation_source
        @helper_live_readback_attested ? "kernel_program_info" : "external_attestation"
      end

      def load_evidence_attested?(program, readback)
        return false unless program.respond_to?(:load_evidence) && program.respond_to?(:load_evidence_sha256)

        evidence = program.load_evidence
        digest = program.load_evidence_sha256
        return false unless evidence.is_a?(Hash) && digest.to_s.match?(/\A[0-9a-f]{64}\z/i)
        return false unless BPF.evidence_digest(evidence) == digest
        return false unless evidence["program_id"].to_i == program.id && evidence["program_tag"].to_s == program.tag.to_s
        return false unless Array(evidence["helper_ids"]).map(&:to_i).sort == Array(program.helper_ids).map(&:to_i).sort
        return false unless Array(evidence["requested_helper_ids"]).map(&:to_i).sort == program_requested_helper_ids(program)
        return false unless Array(evidence["translated_helper_calls"]).map(&:to_i) == program_translated_helper_calls(program)
        return false unless Array(evidence["requested_helper_calls"]).map(&:to_i) == program_requested_helper_calls(program)

        observed = readback.is_a?(Hash) ? readback[:program] || readback["program"] : nil
        return false unless observed.is_a?(Hash)
        observed_id = observed[:id] || observed["id"]
        observed_tag = observed[:tag] || observed["tag"]
        return false unless observed_id.to_i == program.id && observed_tag.to_s == program.tag.to_s
        observed_helpers = observed[:helper_ids] || observed["helper_ids"] || observed[:helperIds] || observed["helperIds"]
        Array(observed_helpers).map(&:to_i).sort == Array(program.helper_ids).map(&:to_i).sort
      rescue StandardError
        false
      end

      def helper_attestation_for(program, external)
        @helper_live_readback_attested = false
        requested_helper_calls = program_requested_helper_calls(program)
        translated_helper_calls = program_translated_helper_calls(program)
        # A readback that returns helper metadata is authoritative.  Do not
        # fall through to an external report when it disagrees with the
        # loaded Program; that would let a caller replace a live observation
        # with attacker-controlled helper IDs.
        live_readback = begin
          program_info_readback(program)
        rescue StandardError
          nil
        end
        if live_readback
          live_helper_ids = helper_ids_from_hash(live_readback)
          if live_helper_ids
            return nil unless live_program_readback_matches?(program, live_readback, live_helper_ids)

            # Preserve the content-bound load-evidence gate.  A live helper
            # set is authoritative, but it is not sufficient to attest a
            # production load without the existing verifier/evidence checks.
            return nil unless requested_helper_calls.include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP) &&
                              helper_call_counts_consistent?(requested_helper_calls, translated_helper_calls) &&
                              load_evidence_attested?(program, {program: live_readback})

            @helper_live_readback_attested = true
            return kernel_helper_attestation(program, live_helper_ids)
          end
        end

        # No usable BPF_OBJ_GET_INFO_BY_FD result was available.  The
        # external path is retained for compatibility, but attach marks it
        # non-production and the helper IDs must still equal Program#helper_ids.
        external_helper_attestation(program, external)
      rescue StandardError
        @helper_live_readback_attested = false
        nil
      end

      # The translated stream returned by BPF_OBJ_GET_INFO_BY_FD is not a
      # one-to-one image of the requested stream: do_misc_fixups rewrites
      # every remaining BPF_CALL immediate to a kernel function address and,
      # since Linux 6.0, inlines bpf_loop when its callback is a static
      # subprogram called with zero flags.  A consistent readback therefore
      # has either every requested call or every call except the inlined
      # bpf_loop invocations; any other count means the kernel verified a
      # different program than the one this adapter assembled.
      def helper_call_counts_consistent?(requested_calls, translated_calls)
        requested = Array(requested_calls)
        translated = Array(translated_calls)
        return false if requested.empty? || translated.empty?

        inlined_loops = requested.count(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP)
        # array_map_gen_lookup (Linux >= 4.14, JIT enabled) also replaces a
        # map_lookup_elem call on an ARRAY map with inline code; hash, LRU,
        # and LPM lookups keep a BPF_CALL to their map-specific function.
        inlined_array_lookups = @inlinable_array_lookups.to_i
        expected_counts = [0, inlined_loops].product([0, inlined_array_lookups]).map { |loops, arrays| requested.length - loops - arrays }
        expected_counts.uniq.include?(translated.length)
      end

      # Count the requested map_lookup_elem calls whose operand is an ARRAY
      # map so the translated-call accounting knows how many the kernel may
      # legitimately inline.  The map operand is the most recent ldimm64
      # BPF_PSEUDO_MAP_FD before the call, which is how the assembler emits
      # every lookup.
      def count_inlinable_array_lookups(instructions, maps)
        array_fds = Array(maps).filter_map do |entry|
          _name, map = entry
          map.fd if map.respond_to?(:type) && map.type == BPF::BPF_MAP_TYPE_ARRAY
        end
        return 0 if array_fds.empty?

        last_map_fd = nil
        Array(instructions).count do |instruction|
          if instruction.code == (BPF::BPF_LD | BPF::BPF_DW | BPF::BPF_IMM) &&
             instruction.source == EBPFProgram::Assembler::BPF_PSEUDO_MAP_FD
            last_map_fd = instruction.immediate
            false
          elsif instruction.code == (BPF::BPF_JMP | EBPFProgram::Assembler::BPF_CALL) && instruction.source.zero?
            lookup = instruction.immediate == EBPFProgram::ServiceDatapath::HELPER_MAP_LOOKUP && array_fds.include?(last_map_fd)
            last_map_fd = nil
            lookup
          else
            false
          end
        end
      end

      def live_program_readback_matches?(program, readback, helper_ids)
        return false unless readback.is_a?(Hash)

        readback_id = if readback.key?(:id)
                        readback[:id]
                      elsif readback.key?("id")
                        readback["id"]
                      end
        readback_tag = if readback.key?(:tag)
                         readback[:tag]
                       elsif readback.key?("tag")
                         readback["tag"]
                       end
        return false if readback_id.nil? || readback_tag.nil? || program.id.nil?

        readback_id.to_i == program.id && readback_tag.to_s == program.tag.to_s &&
          helper_ids == program_helper_ids(program)
      end

      def kernel_helper_attestation(program, helper_ids)
        document = {
          "source" => "kernel_program_info",
          "helperIds" => helper_ids,
          "requestedHelperIds" => program_requested_helper_ids(program),
          "translatedHelperCalls" => program_translated_helper_calls(program),
          "requestedHelperCalls" => program_requested_helper_calls(program),
          "programId" => program.id,
          "programTag" => program.tag,
          "loadEvidenceSha256" => program.load_evidence_sha256
        }.freeze
        document.merge("attestationSha256" => BPF.evidence_digest(document)).freeze
      end

      # The adapter readback has already been performed before this method is
      # called. Re-fetching program_info here is intentional: an external
      # observer must not be able to promote stale in-process data to a live
      # helper claim after the program has been replaced.
      def program_info_readback(program)
        @bpf.program_info(program, resource_id: "proxy:ebpf:program:helper-readback")
      end

      def external_helper_attestation(program, attestation)
        return nil unless attestation.respond_to?(:each_pair)

        source = attestation["source"] || attestation[:source]
        helper_ids = Array(attestation["helperIds"] || attestation[:helperIds] ||
                           attestation["helper_ids"] || attestation[:helper_ids]).map(&:to_i).uniq.sort.freeze
        requested_helper_ids = Array(attestation["requestedHelperIds"] || attestation[:requestedHelperIds] ||
                                     attestation["requested_helper_ids"] || attestation[:requested_helper_ids]).map(&:to_i).uniq.sort.freeze
        if requested_helper_ids.empty? && program.respond_to?(:load_evidence) && program.load_evidence.is_a?(Hash)
          requested_helper_ids = Array(program.load_evidence["requested_helper_ids"]).map(&:to_i).uniq.sort.freeze
        end
        requested_helper_calls = Array(attestation["requestedHelperCalls"] || attestation[:requestedHelperCalls] ||
                                       attestation["requested_helper_calls"] || attestation[:requested_helper_calls]).map(&:to_i).freeze
        if requested_helper_calls.empty? && program.respond_to?(:load_evidence) && program.load_evidence.is_a?(Hash)
          requested_helper_calls = Array(program.load_evidence["requested_helper_calls"]).map(&:to_i).freeze
        end
        translated_helper_calls = Array(attestation["translatedHelperCalls"] || attestation[:translatedHelperCalls] ||
                                        attestation["translated_helper_calls"] || attestation[:translated_helper_calls]).map(&:to_i).freeze
        program_id = attestation["programId"] || attestation[:programId] ||
          attestation["program_id"] || attestation[:program_id]
        program_tag = attestation["programTag"] || attestation[:programTag] ||
          attestation["program_tag"] || attestation[:program_tag]
        load_digest = attestation["loadEvidenceSha256"] || attestation[:loadEvidenceSha256] ||
          attestation["load_evidence_sha256"] || attestation[:load_evidence_sha256]
        evidence_digest = attestation["attestationSha256"] || attestation[:attestationSha256] ||
          attestation["attestation_sha256"] || attestation[:attestation_sha256] ||
          attestation["evidenceSha256"] || attestation[:evidenceSha256] ||
          attestation["evidence_sha256"] || attestation[:evidence_sha256]
        document = {
          "source" => source.to_s,
          "helperIds" => helper_ids,
          "requestedHelperIds" => requested_helper_ids,
          "requestedHelperCalls" => requested_helper_calls,
          "translatedHelperCalls" => translated_helper_calls,
          "programId" => program_id.to_i,
          "programTag" => program_tag.to_s,
          "loadEvidenceSha256" => load_digest.to_s
        }.freeze
        return nil if document["source"].empty? || document["source"] == "model_only"
        return nil if helper_ids.empty?
        # The external document is not a kernel observation.  Even when the
        # live info syscall is unavailable, it may only describe the exact
        # helper set already bound to this immutable Program object; a caller
        # cannot substitute a more permissive helper set with a self-hash.
        return nil unless helper_ids == program_helper_ids(program)
        return nil unless requested_helper_ids == program_requested_helper_ids(program)
        return nil unless requested_helper_calls == program_requested_helper_calls(program)
        return nil unless translated_helper_calls == program_translated_helper_calls(program)
        return nil unless requested_helper_ids.include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP)
        return nil unless requested_helper_calls.include?(EBPFProgram::ServiceDatapath::HELPER_BPF_LOOP)
        return nil unless helper_call_counts_consistent?(requested_helper_calls, translated_helper_calls)
        return nil unless document["programId"] == program.id && document["programTag"] == program.tag.to_s
        return nil unless document["loadEvidenceSha256"].match?(/\A[0-9a-f]{64}\z/i)
        return nil unless document["loadEvidenceSha256"] == program.load_evidence_sha256.to_s
        return nil unless evidence_digest.to_s.match?(/\A[0-9a-f]{64}\z/i)
        # This digest detects accidental document changes only.  It is not a
        # trust boundary; @helper_live_readback_attested remains false for
        # this fallback, so production capability cannot rely on it.
        return nil unless BPF.evidence_digest(document) == evidence_digest

        document.merge("attestationSha256" => evidence_digest).freeze
      end

      def tc_attach_readback_attested?(readback)
        filters = readback.is_a?(Hash) ? readback[:filters] || readback["filters"] : nil
        expected = @links.map { |link| [link.fetch(:ifindex), link.fetch(:direction), link.fetch(:handle), @program.id] }
        expected.all? do |ifindex, direction, handle, program_id|
          Array(filters).any? do |filter|
            filter[:ifindex].to_i == ifindex && filter[:direction] == direction && filter[:handle].to_i == handle &&
              filter[:program_id].to_i == program_id
          end
        end
      end

      def normalize_name(value)
        name = String(value)
        raise ArgumentError, "BPF object name must not be empty" if name.empty?
        raise ArgumentError, "BPF object name exceeds 15 bytes" if name.bytesize > 15

        name
      end

      def normalize_hooks(hook)
        values = hook.to_sym == :tc ? %i[ingress egress] : [hook.to_sym]
        values.each do |value|
          raise ArgumentError, "unsupported TC hook #{value.inspect}" unless %i[ingress egress].include?(value)
        end
        values.freeze
      rescue NoMethodError
        raise ArgumentError, "TC hook must be ingress, egress, or tc"
      end

      # Accept one interface/ifindex or a list of them; the first entry is
      # the identity reported in attach results.
      ACCEPT_LOCAL_SYSCTL = "/proc/sys/net/ipv4/conf/%s/accept_local"

      def configure_accept_local!(ifindices)
        @accept_local_restore = {}
        ifindices.each do |index|
          name = Socket.getifaddrs.find { |address| address.ifindex == index }&.name
          next unless name

          path = format(ACCEPT_LOCAL_SYSCTL, name)
          next unless File.file?(path)

          previous = File.read(path).strip
          next if previous == "1"

          File.write(path, "1\n")
          @accept_local_restore[path] = previous
        end
      end

      def restore_accept_local!
        Hash(@accept_local_restore).each do |path, previous|
          File.write(path, "#{previous}\n") if File.file?(path)
        end
        @accept_local_restore = {}
      end

      def resolve_ifindices(interface:, ifindex:)
        interfaces = interface.is_a?(Array) ? interface : [interface]
        ifindices = ifindex.is_a?(Array) ? ifindex : [ifindex]
        pairs = interfaces.length >= ifindices.length ? interfaces.each_with_index.map { |name, index| [name, ifindices[index]] } : ifindices.each_with_index.map { |value, index| [interfaces[index], value] }
        resolved = pairs.map { |name, value| resolve_ifindex(interface: name, ifindex: value) }.uniq
        raise ArgumentError, "at least one TC interface is required" if resolved.empty?

        resolved.freeze
      end

      def resolve_ifindex(interface:, ifindex:)
        ifindex_value = ifindex.nil? ? nil : Integer(ifindex)
        return ifindex_value if ifindex_value && ifindex_value.positive?

        name = String(interface || "")
        raise ArgumentError, "a real interface name or positive ifindex is required for TC attach" if name.empty?

        entry = Socket.getifaddrs.find { |address| address.name == name && address.ifindex }
        resolved = entry&.ifindex
        raise Errno::ENODEV, "interface #{name.inspect} was not found" unless resolved && resolved.positive?

        resolved
      rescue TypeError, ArgumentError => error
        raise ArgumentError, "invalid TC interface reference: #{error.message}"
      end

      def normalize_map_layout(layout)
        raise ArgumentError, "eBPF map layout must be a non-empty hash" unless layout.respond_to?(:each_pair) && !layout.empty?
        names = layout.keys.map(&:to_s)
        raise ArgumentError, "sctp_crc32c map is mandatory for every eBPF proxy layout" unless names.include?("sctp_crc32c")

        layout.each_with_object({}) do |(name, spec), normalized|
          logical_name = String(name)
          raise ArgumentError, "BPF map name must not be empty" if logical_name.empty?
          raise ArgumentError, "BPF map #{logical_name} specification must be a hash" unless spec.respond_to?(:transform_keys)

          kernel_name = logical_name.bytesize <= 15 ? logical_name : "rk_#{Digest::SHA256.hexdigest(logical_name)[0, 12]}"
          values = spec.transform_keys(&:to_s)
          type = values.fetch("type").to_s
          key_size = Integer(values.fetch("key_size"))
          value_size = Integer(values.fetch("value_size"))
          max_entries = Integer(values.fetch("max_entries"))
          raise ArgumentError, "map #{logical_name} key_size must be positive" unless key_size.positive?
          raise ArgumentError, "map #{logical_name} value_size must be positive" unless value_size.positive?
          raise ArgumentError, "map #{logical_name} max_entries must be positive" unless max_entries.positive?
          normalized[logical_name] = {name: kernel_name, type: type, key_size: key_size, value_size: value_size,
                                      max_entries: max_entries, flags: Integer(values.fetch("flags", 0))}.freeze
        end.freeze
      rescue KeyError, TypeError, ArgumentError => error
        raise ArgumentError, "invalid eBPF map layout: #{error.message}"
      end

      def create_map(name, spec, ifindex:)
        map_type = case spec.fetch(:type)
                   when "hash" then BPF::BPF_MAP_TYPE_HASH
                   when "lru_hash" then BPF::BPF_MAP_TYPE_LRU_HASH
                   when "lpm_trie" then BPF::BPF_MAP_TYPE_LPM_TRIE
                   when "array" then BPF::BPF_MAP_TYPE_ARRAY
                   when "array_of_structs"
                     # Linux has no array-of-structs map type. A hash with the
                     # declared fixed key preserves the existing wire layout.
                     BPF::BPF_MAP_TYPE_HASH
                   else
                     raise ArgumentError, "unsupported eBPF map type #{spec.fetch(:type).inspect}"
                   end
        flags = spec.fetch(:flags)
        flags |= BPF::BPF_F_NO_PREALLOC if [BPF::BPF_MAP_TYPE_HASH, BPF::BPF_MAP_TYPE_LPM_TRIE].include?(map_type)
        # Generic hash/array maps are namespace-scoped, not netdev-scoped;
        # BPF_MAP_CREATE rejects a non-zero map_ifindex for these types.
        @bpf.map_create(type: map_type, key_size: spec.fetch(:key_size), value_size: spec.fetch(:value_size),
                        max_entries: spec.fetch(:max_entries), map_flags: flags, name: spec.fetch(:name), ifindex: 0,
                        resource_id: "proxy:ebpf:map:#{name}")
      end

      def sync_maps(maps, rules)
        service_rules = Array(rules)
        initialize_sctp_crc32c_map(maps["sctp_crc32c"]) if maps["sctp_crc32c"] && !@crc32c_initialized
        next_service_keys = current_service_keys(service_rules)
        @service_keys.each_value do |key|
          next if next_service_keys.value?(key)

          delete_map_entry(maps.fetch("service_rules"), key, "service_rule")
        end
        # Backend values are retained across ruleset revisions. Conntrack
        # values contain the selected backend address directly, but retaining
        # the slot also lets an affinity entry finish its timeout without a
        # transient blackhole when the EndpointSlice changes.
        service_rules.each do |rule|
          service_rule_families(rule).each do |family|
            service_key, service_value = encode_service_rule_for_family(rule, family)
            update_map_entry(maps.fetch("service_rules"), service_key, service_value, "service_rule")
            backend_candidates(rule).select { |backend| backend_family(backend) == family }.each_with_index do |backend, index|
              backend_key, backend_value = encode_backend(backend, token: service_token(rule), index: index,
                                                          family: family)
              update_map_entry(maps.fetch("backends"), backend_key, backend_value, "backend")
            end
          end
        end
        next_source_ranges = current_source_range_entries(service_rules)
        if next_source_ranges.any? && !maps.key?("source_ranges")
          raise ArgumentError, "source_ranges map is required for LoadBalancer source ranges"
        end
        requires_snat = service_rules.any? do |rule|
          service_rule_families(rule).any? do |family|
            service_flags(rule, family) & (EBPFProgram::WireFormat::SERVICE_FLAG_MASQUERADE |
                                           EBPFProgram::WireFormat::SERVICE_FLAG_HAIRPIN) != 0
          end
        end
        raise ArgumentError, "snat map is required for masquerade or hairpin rules" if requires_snat && !maps.key?("snat")
        if maps.key?("source_ranges")
          @source_range_keys.each_value do |key|
            next if next_source_ranges.key?(key)

            delete_map_entry(maps.fetch("source_ranges"), key, "source_range")
          end
          next_source_ranges.each do |key, value|
            update_map_entry(maps.fetch("source_ranges"), key, value, "source_range")
          end
        end
      end

      def initialize_sctp_crc32c_map(map)
        256.times do |index|
          key = [index].pack("L<")
          value = [sctp_crc32c_table_value(index)].pack("L<")
          update_map_entry(map, key, value, "sctp_crc32c")
        end
        @crc32c_initialized = true
      end

      def sctp_crc32c_table_value(index)
        crc = Integer(index)
        8.times do
          crc = (crc >> 1) ^ ((crc & 1).positive? ? 0x82f63b78 : 0)
        end
        crc & 0xffff_ffff
      end

      def current_service_keys(rules)
        Array(rules).each_with_object({}) do |rule, result|
          service_rule_families(rule).each do |family|
            key, = encode_service_rule_for_family(rule, family)
            result[[rule.key, family].freeze] = key
          end
        end
      end

      def current_backend_keys(rules)
        Array(rules).each_with_object({}) do |rule, result|
          service_rule_families(rule).each do |family|
            backend_candidates(rule).select { |backend| backend_family(backend) == family }.each_with_index do |backend, index|
              key, = encode_backend(backend, token: service_token(rule), index: index, family: family)
              identity = [rule.key, family, backend_identity(backend), index].join("|")
              result[identity] = key
            end
          end
        end
      end

      def current_source_range_keys(rules)
        current_source_range_entries(rules).each_with_object({}) do |(key, _value), result|
          result[Digest::SHA256.hexdigest(key)] = key
        end
      end

      def current_source_range_entries(rules)
        Array(rules).each_with_object({}) do |rule, result|
          next unless rule.kind.to_s == "LoadBalancer"

          source_ranges_for(rule).each do |range|
            range_key, range_value = encode_source_range(rule, range)
            result[range_key] = range_value
          end
        end
      end

      def update_map_entry(map, key, value, resource)
        @bpf.map_update(map: map, key: key, value: value, resource_id: "proxy:ebpf:#{resource}:update")
      end

      def delete_map_entry(map, key, resource)
        @bpf.map_delete(map: map, key: key, resource_id: "proxy:ebpf:#{resource}:delete")
      rescue Rubernetes::Platform::Linux::Error => error
        raise unless error.errno == Errno::ENOENT::Errno
      end

      def encode_service_rule(rule)
        encode_service_rule_for_family(rule, service_rule_families(rule).first)
      end

      def encode_service_rule_for_family(rule, family)
        protocol = PROTOCOLS.fetch(rule.protocol.to_s.upcase, 0)
        virtual_ip = packed_ip(rule.virtual_ip)
        key_port = rule.node_port || rule.port
        key_node_port = rule.node_port || 0
        key = [Integer(family), protocol, Integer(key_port), Integer(key_node_port), 0].pack("CCS<S<S<") +
              virtual_ip + ("\0".b * 16)
        candidates = backend_candidates(rule).select { |backend| backend_family(backend) == Integer(family) }
        value = "\0".b * 64
        value[0, 8] = service_token(rule)
        value.setbyte(8, EBPFProgram::WireFormat::SERVICE_KIND.fetch(rule.kind, 0))
        value.setbyte(9, rule.session_affinity.to_s == "ClientIP" ? 1 : 0)
        # Port bytes in values are copied directly into the skb; retain
        # network order there. The service-map key remains host-endian because
        # the program normalizes the packet port before hash lookup.
        value[12, 2] = [Integer(rule.port)].pack("n")
        value[14, 2] = [Integer(rule.node_port || 0)].pack("n")
        if Integer(family) == 6
          value[20, 4] = [candidates.length].pack("L<")
        else
          value[16, 4] = [candidates.length].pack("L<")
        end
        value[24, 4] = [Integer(rule.session_affinity_timeout_seconds)].pack("L<")
        value[28, 16] = virtual_ip
        value[44, 16] = node_address_for(rule, family)
        value.setbyte(60, service_flags(rule, family))
        [key, value]
      end

      def service_flags(rule, family)
        flags = 0
        node_address = node_address_for(rule, family)
        has_node_address = node_address.bytes.any?(&:positive?)
        flags |= EBPFProgram::WireFormat::SERVICE_FLAG_MASQUERADE if external_rule?(rule) && rule.external_traffic_policy.to_s == "Cluster" && has_node_address
        flags |= EBPFProgram::WireFormat::SERVICE_FLAG_HAIRPIN if has_node_address
        flags |= EBPFProgram::WireFormat::SERVICE_FLAG_HEALTH_CHECK if rule.health_check
        flags |= EBPFProgram::WireFormat::SERVICE_FLAG_SOURCE_RANGES if rule.kind.to_s == "LoadBalancer" && source_ranges_for(rule).any?
        flags
      end

      def node_address_for(rule, family)
        metadata = rule.respond_to?(:metadata) ? rule.metadata : {}
        addresses = Array(metadata["nodeAddresses"] || metadata[:nodeAddresses] || metadata["node_addresses"] || metadata[:node_addresses])
        selected = addresses.find do |address|
          backend_family(Struct.new(:address).new(address)) == Integer(family)
        end
        packed_ip(selected)
      end

      def external_rule?(rule)
        %w[NodePort ExternalIP LoadBalancer HealthCheckNodePort].include?(rule.kind.to_s)
      end

      def encode_source_range(rule, range)
        ip = IPAddr.new(range.to_s)
        prefix_length = 64 + (ip.ipv4? ? 96 : 0) + ip.prefix
        key = [prefix_length].pack("L<") + service_token(rule) + packed_ip(ip.to_s)
        [key, [1].pack("L<")]
      rescue IPAddr::InvalidAddressError => error
        raise ArgumentError, "invalid load balancer source range #{range.inspect}: #{error.message}"
      end

      def source_ranges_for(rule)
        metadata = rule.respond_to?(:metadata) ? rule.metadata : {}
        Array(metadata["loadBalancerSourceRanges"] || metadata[:loadBalancerSourceRanges] ||
              metadata["load_balancer_source_ranges"] || metadata[:load_balancer_source_ranges]).map(&:to_s).reject(&:empty?)
      end

      def encode_backend(backend, token: nil, index: nil, family: nil)
        identity = backend_identity(backend)
        digest = Digest::SHA256.digest(identity)[0, 16]
        address = packed_ip(backend.respond_to?(:address) ? backend.address : nil)
        port = backend.respond_to?(:port) ? Integer(backend.port) : 0
        protocol = PROTOCOLS.fetch(backend.respond_to?(:protocol) ? backend.protocol.to_s.upcase : "", 0)
        family ||= backend_family(backend)
        key = if token && !index.nil?
                token.to_s.b.ljust(8, "\0".b)[0, 8] + [backend_slot(index, family)].pack("L<") + ("\0".b * 4)
              else
                digest
              end
        value = address + [port].pack("n") + [protocol, Integer(family)].pack("CC")
        [key, value.ljust(96, "\0".b)[0, 96]]
      end

      def service_token(rule)
        Digest::SHA256.digest(rule.key.to_s)[0, EBPFProgram::WireFormat::SERVICE_TOKEN_SIZE]
      end

      def backend_slot(index, family)
        slot = Integer(index)
        raise ArgumentError, "backend slot must be non-negative" if slot.negative?
        raise ArgumentError, "backend slot exceeds IPv6 marker" if slot >= EBPFProgram::WireFormat::IPV6_SLOT_BIT

        Integer(family) == 6 ? (slot | EBPFProgram::WireFormat::IPV6_SLOT_BIT) : slot
      end

      def backend_family(backend)
        if backend.respond_to?(:family)
          %w[IPv6 ipv6 6].include?(backend.family.to_s) ? 6 : 4
        elsif backend.respond_to?(:address) && backend.address.to_s.include?(":")
          6
        else
          4
        end
      end

      def service_rule_families(rule)
        return [rule.virtual_ip.to_s.include?(":") ? 6 : 4] unless rule.virtual_ip.nil?

        metadata = rule.respond_to?(:metadata) ? rule.metadata : {}
        configured = metadata["serviceFamilies"] || metadata[:serviceFamilies]
        families = Array(configured).filter_map do |value|
          value.to_s.include?("6") ? 6 : (value.to_s.include?("4") ? 4 : nil)
        end
        families = rule.backends.map { |backend| backend_family(backend) }.uniq if families.empty?
        (families.empty? ? [4] : families).uniq.sort.freeze
      end

      def backend_candidates(rule)
        all = Array(rule.backends)
        metadata = rule.respond_to?(:metadata) ? rule.metadata : {}
        groups = metadata["backendGroups"] || metadata[:backendGroups] || {}
        by_identity = all.each_with_object({}) { |backend, result| result[backend_identity(backend)] = backend }
        all_ids = Array(groups["all"] || groups[:all]).map(&:to_s)
        local_ids = Array(groups["local"] || groups[:local]).map(&:to_s)
        healthy_ids = Array(groups["healthy"] || groups[:healthy]).map(&:to_s)
        serving_ids = Array(groups["serving"] || groups[:serving]).map(&:to_s)
        terminating_ids = Array(groups["terminating"] || groups[:terminating]).map(&:to_s)
        selected_ids = all_ids.empty? ? by_identity.keys : all_ids
        local_node = metadata["node"] || metadata[:node]
        if %w[NodePort ExternalIP LoadBalancer HealthCheckNodePort].include?(rule.kind.to_s)
          selected_ids &= local_ids if rule.external_traffic_policy.to_s == "Local" && !local_node.to_s.empty?
        elsif rule.kind.to_s == "ClusterIP"
          selected_ids &= local_ids if rule.internal_traffic_policy.to_s == "Local" && !local_node.to_s.empty?
        end
        selected = selected_ids.filter_map { |identity| by_identity[identity] }
        healthy_selected = if healthy_ids.empty?
                             selected.select { |backend| endpoint_healthy?(backend) }
                           else
                             selected.select { |backend| healthy_ids.include?(backend_identity(backend)) }
                           end
        selected = if publish_not_ready_addresses?(rule)
                     non_terminating = selected.reject { |backend| endpoint_terminating?(backend) }
                     if non_terminating.any?
                       non_terminating
                     else
                       selected.select do |backend|
                         identity = backend_identity(backend)
                         terminating = terminating_ids.empty? ? endpoint_terminating?(backend) : terminating_ids.include?(identity)
                         serving = serving_ids.empty? ? endpoint_serving?(backend) : serving_ids.include?(identity)
                         terminating && serving
                       end
                     end
                   elsif healthy_selected.any?
                     healthy_selected
                   else
                     terminating_selected = selected.select do |backend|
                       identity = backend_identity(backend)
                       terminating = terminating_ids.empty? ? endpoint_terminating?(backend) : terminating_ids.include?(identity)
                       serving = serving_ids.empty? ? endpoint_serving?(backend) : serving_ids.include?(identity)
                       terminating && serving
                     end
                     if terminating_selected.any?
                       terminating_selected
                     else
                       []
                     end
                   end
        if rule_topology_hints_enabled?(rule)
          zone = metadata["zone"] || metadata[:zone]
          if zone && !zone.to_s.empty? && selected.all? { |backend| backend.respond_to?(:hints) && !Array(backend.hints).empty? }
            hinted = selected.select { |backend| Array(backend.hints).map(&:to_s).include?(zone.to_s) }
            selected = hinted unless hinted.empty?
          end
        end
        selected.sort_by { |backend| backend_identity(backend) }
      end

      def publish_not_ready_addresses?(rule)
        metadata = rule.respond_to?(:metadata) ? rule.metadata : {}
        ModelSupport.bool(metadata["publishNotReadyAddresses"] || metadata[:publishNotReadyAddresses], false)
      end

      def endpoint_healthy?(backend)
        return backend.healthy? if backend.respond_to?(:healthy?)

        ready = backend.respond_to?(:ready) ? backend.ready : true
        serving = backend.respond_to?(:serving?) ? backend.serving? : true
        terminating = backend.respond_to?(:terminating?) ? backend.terminating? : false
        !!ready && !!serving && !terminating
      end

      def endpoint_serving?(backend)
        backend.respond_to?(:serving?) ? backend.serving? : true
      end

      def endpoint_terminating?(backend)
        backend.respond_to?(:terminating?) ? backend.terminating? : false
      end

      def rule_topology_hints_enabled?(rule)
        metadata = rule.respond_to?(:metadata) ? rule.metadata : {}
        value = metadata["topologyAwareHints"] || metadata[:topologyAwareHints]
        value.nil? || ModelSupport.bool(value, true)
      end

      def backend_identity(backend)
        backend.respond_to?(:identity) ? backend.identity.to_s : backend.to_s
      end

      def packed_ip(value)
        return ("\0".b * 16) if value.nil? || value.to_s.empty?

        ip = IPAddr.new(value.to_s)
        ip.ipv4? ? ("\0".b * 10) + "\xff\xff".b + ip.hton : ip.hton
      rescue IPAddr::InvalidAddressError => error
        raise ArgumentError, "invalid backend or service IP #{value.inspect}: #{error.message}"
      end

      def tcmsg(ifindex:, handle:, parent:, info: 0)
        [AF_UNSPEC, 0, 0, Integer(ifindex), Integer(handle), Integer(parent), Integer(info)]
          .pack("CCS<l<L<L<L<")
      end

      def ensure_clsact(ifindex)
        attributes = [TCNetlink.attribute(TCA_KIND, "clsact\0")]
        @netlink.request(type: RTM_NEWQDISC, flags: NLM_F_REQUEST | NLM_F_ACK | NLM_F_CREATE | NLM_F_EXCL,
                         payload: tcmsg(ifindex: ifindex, handle: 0xffff_0000, parent: TC_H_CLSACT), attributes: attributes,
                         resource_id: "proxy:tc:#{ifindex}:clsact")
      rescue Rubernetes::Platform::Linux::Error => error
        raise unless error.errno == Errno::EEXIST::Errno
      end

      def attach_filter(ifindex, direction, program)
        parent = direction == :ingress ? TC_PARENT_INGRESS : TC_PARENT_EGRESS
        handle = DEFAULT_HANDLE + (direction == :ingress ? 1 : 2)
        info = (DEFAULT_PRIORITY << 16) | ETH_P_ALL_NETWORK
        options = [
          TCNetlink.attribute(TCA_BPF_FD, [program.fd].pack("L<")),
          TCNetlink.attribute(TCA_BPF_NAME, "#{@program_name}\0"),
          TCNetlink.attribute(TCA_BPF_FLAGS, [TCA_BPF_FLAG_ACT_DIRECT].pack("L<"))
        ].join
        attributes = [TCNetlink.attribute(TCA_KIND, "bpf\0"), TCNetlink.attribute(TCA_OPTIONS, options, nested: true)]
        @netlink.request(type: RTM_NEWTFILTER,
                         # Refuse to replace an unrelated filter occupying our
                         # deterministic handle; ownership must be explicit.
                         flags: NLM_F_REQUEST | NLM_F_ACK | NLM_F_CREATE | NLM_F_EXCL,
                         payload: tcmsg(ifindex: ifindex, handle: handle, parent: parent, info: info),
                         attributes: attributes, resource_id: "proxy:tc:#{ifindex}:#{direction}")
        {ifindex: ifindex, direction: direction, parent: parent, handle: handle, priority: DEFAULT_PRIORITY,
         program_id: program.id}.freeze
      end

      def delete_filter(ifindex, link)
        parent = Integer(link.fetch(:parent))
        handle = Integer(link.fetch(:handle))
        info = (Integer(link.fetch(:priority, DEFAULT_PRIORITY)) << 16) | ETH_P_ALL_NETWORK
        attributes = [TCNetlink.attribute(TCA_KIND, "bpf\0")]
        @netlink.request(type: RTM_DELTFILTER, flags: NLM_F_REQUEST | NLM_F_ACK,
                         payload: tcmsg(ifindex: ifindex, handle: handle, parent: parent, info: info),
                         attributes: attributes, resource_id: "proxy:tc:#{ifindex}:delete")
      rescue Rubernetes::Platform::Linux::Error => error
        raise unless error.errno == Errno::ENOENT::Errno
      end

      def verify_kernel_state(ifindex)
        raise RuntimeError, "program is not loaded" unless @program

        program_info = @bpf.program_info(@program, resource_id: "proxy:ebpf:program:readback")
        unless program_info[:id] == @program.id && program_info[:tag].to_s == @program.tag.to_s &&
               Array(program_info[:helper_ids]).map(&:to_i).sort == Array(@program.helper_ids).map(&:to_i).sort
          raise RuntimeError, "BPF program readback identity or helper metadata differs from the loaded program"
        end
        map_info = @maps.each_with_object({}) do |(name, map), result|
          result[name] = @bpf.map_info(map, resource_id: "proxy:ebpf:map:#{name}:readback")
        end
        filter_info = read_filters(ifindex)
        expected_ids = @links.map { |link| [link.fetch(:ifindex), link.fetch(:direction), link.fetch(:handle)] }
        actual_ids = filter_info.filter_map do |entry|
          next unless entry[:program_id] == @program.id

          [entry[:ifindex], entry[:direction], entry[:handle]]
        end
        unless expected_ids.all? { |identity| actual_ids.include?(identity) }
          raise RuntimeError, "TC filter readback did not contain the loaded program identity"
        end
        {program: program_info, maps: map_info.freeze, filters: filter_info.freeze}.freeze
      end

      # Every owned link is read back on its own device; the ifindex argument
      # only names the primary device for callers that still pass it.
      def read_filters(_ifindex = nil)
        Array(@links).flat_map do |link|
          link_ifindex = link.fetch(:ifindex)
          messages = @netlink.request(type: RTM_GETTFILTER, flags: NLM_F_DUMP,
                                      payload: tcmsg(ifindex: link_ifindex, handle: 0, parent: link.fetch(:parent)),
                                      attributes: [], resource_id: "proxy:tc:#{link_ifindex}:#{link.fetch(:direction)}:readback")
          Array(messages).filter_map { |message| parse_filter(message.payload, link_ifindex) }
        end
      end

      def parse_filter(payload, ifindex)
        bytes = String(payload).b
        return nil if bytes.bytesize < TCMSG_SIZE

        _family, _pad1, _pad2, message_ifindex, handle, parent, info = bytes.byteslice(0, TCMSG_SIZE)
          .unpack("CCS<l<L<L<L<")
        return nil unless message_ifindex == Integer(ifindex)

        attributes = decode_attributes(bytes.byteslice(TCMSG_SIZE..))
        kind = attributes.find { |entry| entry[:type] == TCA_KIND }&.fetch(:value, "").to_s.delete_suffix("\0")
        return nil unless kind == "bpf"

        options = attributes.find { |entry| entry[:type] == TCA_OPTIONS }
        nested = options ? decode_attributes(options.fetch(:value)) : []
        program_id_bytes = nested.find { |entry| entry[:type] == TCA_BPF_ID }&.fetch(:value)
        return nil unless program_id_bytes && program_id_bytes.bytesize >= 4

        direction = case parent & 0xffff
                    when TC_H_MIN_INGRESS & 0xffff then :ingress
                    when TC_H_MIN_EGRESS & 0xffff then :egress
                    else :unknown
                    end
        {ifindex: message_ifindex, handle: handle, parent: parent, info: info,
         priority: info >> 16, direction: direction, program_id: program_id_bytes.unpack1("L<")}.freeze
      end

      def decode_attributes(bytes)
        buffer = String(bytes || "").b
        attributes = []
        offset = 0
        while offset + 4 <= buffer.bytesize
          length, type = buffer.byteslice(offset, 4).unpack("S<S<")
          break if length < 4 || offset + length > buffer.bytesize

          attributes << {type: type & 0x3fff, nested: (type & 0x8000).positive?,
                         value: buffer.byteslice(offset + 4, length - 4).freeze}
          offset += TCNetlink.align(length)
        end
        raise IOError, "TC attribute stream is truncated" unless offset == buffer.bytesize

        attributes
      end

      def result_for(readback)
        program = readback.fetch(:program).slice(:id, :type, :name, :ifindex, :tag).merge(
          helper_ids: observed_helper_ids,
          verifier_log_sha256: @program.verifier_log_sha256,
          load_evidence_sha256: @program.load_evidence_sha256,
          xlated_program_sha256: @program.xlated_program_sha256,
          translated_helper_calls: program_translated_helper_calls(@program),
          verified_insns: @program.verified_insns
        )
        {
          verified: true,
          interface: {ifindex: @links.first.fetch(:ifindex)},
          verifier_log_sha256: @program.verifier_log_sha256,
          load_evidence_sha256: @program.load_evidence_sha256,
          helper_ids: observed_helper_ids,
          helper_observation_source: helper_observation_source,
          helper_readback_attested: @helper_live_readback_attested,
          requested_helper_ids: program_requested_helper_ids(@program),
          requested_helper_calls: program_requested_helper_calls(@program),
          program: program,
          maps: readback.fetch(:maps).transform_values do |info|
            info.slice(:id, :type, :key_size, :value_size, :max_entries, :flags, :name, :ifindex)
          end,
          links: @links,
          filters: readback.fetch(:filters)
        }.freeze
      end

      def identity_matches?(result, readback)
        program = result.fetch(:program)
        observed_program = readback.fetch(:program)
        program.fetch(:id) == observed_program.fetch(:id) &&
          program.fetch(:type) == observed_program.fetch(:type) &&
          program.fetch(:name) == observed_program.fetch(:name) &&
          program.fetch(:ifindex) == observed_program.fetch(:ifindex) &&
          program.fetch(:tag) == observed_program.fetch(:tag) &&
          result.fetch(:maps).all? do |name, value|
            observed_map = readback.fetch(:maps).fetch(name)
            value.slice(:id, :type, :key_size, :value_size, :max_entries, :flags, :name, :ifindex) ==
              observed_map.slice(:id, :type, :key_size, :value_size, :max_entries, :flags, :name, :ifindex)
          end &&
          result.fetch(:links).all? do |link|
            readback.fetch(:filters).any? do |filter|
              filter[:ifindex] == link[:ifindex] && filter[:handle] == link[:handle] &&
                filter[:program_id] == @program.id
            end
          end
      end

      def expected_program_matches?(expected)
        return false unless expected.is_a?(Hash)

        expected_program = expected[:program] || expected["program"]
        # A caller may name either the backend's abstract program spec that
        # was handed to attach or the exact instruction stream the verifier
        # accepted; both identify the loaded datapath.
        program_matches = expected_program.nil? ||
          (expected_program.is_a?(Array) &&
           (@attached_program_spec == deep_copy_for_compare(expected_program) ||
            (!@loaded_instructions.nil? && expected_program == @loaded_instructions)))
        expected_layout = expected[:map_layout] || expected["map_layout"]
        layout_matches = expected_layout.nil? || canonical_layout(expected_layout) == canonical_layout(@map_layout)
        program_matches && layout_matches
      end

      def canonical_layout(value)
        value.to_h.each_with_object({}) do |(name, spec), result|
          result[name.to_s] = spec.to_h.transform_keys(&:to_s)
        end
      end

      def deep_copy_for_compare(value)
        case value
        when Hash
          value.each_with_object({}) { |(key, child), result| result[key] = deep_copy_for_compare(child) }
        when Array
          value.map { |child| deep_copy_for_compare(child) }
        else
          value
        end
      end

      def deep_freeze(value)
        case value
        when Hash
          value.each { |key, child| deep_freeze(key); deep_freeze(child) }
        when Array
          value.each { |child| deep_freeze(child) }
        end
        value.freeze
      end
    end

    EBPFKernelAdapter = LinuxEBPFAdapter unless const_defined?(:EBPFKernelAdapter, false)
  end
end
