# frozen_string_literal: true

require "json"
require "tmpdir"
require_relative "../test_helper"
require "rubernetes/platform/linux/device_cgroup"

# The device cgroup allowlist compiler against runc v1.4.3's own output:
# test/fixtures/runc/device-filter-v1.4.3.json is generated by runc's
# emulator + eBPF generator (test/conformance/runc/device_filter_oracle), so
# every instruction the kernel receives is the one runc would have loaded.
class DeviceCgroupFilterTest < Minitest::Test
  DeviceCgroup = Rubernetes::Platform::Linux::DeviceCgroup
  FIXTURE = File.expand_path("../fixtures/runc/device-filter-v1.4.3.json", __dir__)

  def fixture
    @fixture ||= JSON.parse(File.read(FIXTURE))
  end

  def compile(rules)
    instructions, license = DeviceCgroup.compile(rules)
    [instructions.map { |instruction| instruction.to_binary.unpack1("H*") }, license]
  end

  def test_every_fixture_vector_matches_runc_byte_for_byte
    assert_equal 16, fixture.length
    fixture.each do |vector|
      if vector["error"]
        error = assert_raises(DeviceCgroup::Error, vector["name"]) { DeviceCgroup.compile(vector["rules"]) }
        assert_equal vector["error"], error.message, vector["name"]
      else
        instructions, license = compile(vector["rules"])
        assert_equal vector["instructions"], instructions, vector["name"]
        assert_equal vector["license"], license, vector["name"]
      end
    end
  end

  def test_default_rules_are_the_containerd_cri_default_list
    vector = fixture.find { |entry| entry["name"] == "containerd-cri-default" }
    assert_equal vector["rules"], DeviceCgroup.rules_for.map(&:to_h)
    privileged = fixture.find { |entry| entry["name"] == "containerd-cri-privileged" }
    assert_equal privileged["rules"], DeviceCgroup.rules_for(privileged: true).map(&:to_h)
    with_devices = fixture.find { |entry| entry["name"] == "containerd-cri-with-devices" }
    devices = [{"type" => "c", "major" => 195, "minor" => 0, "access" => "rw", "allow" => true},
               {"type" => "c", "major" => 195, "minor" => 255, "access" => "rwm", "allow" => true},
               {"type" => "b", "major" => 259, "minor" => -1, "access" => "r", "allow" => true}]
    assert_equal with_devices["rules"], DeviceCgroup.rules_for(devices: devices).map(&:to_h)
  end

  def test_privileged_program_is_allow_all_and_default_program_denies_by_default
    instructions, = compile(DeviceCgroup.rules_for(privileged: true))
    assert_equal %w[b400000001000000 9500000000000000], instructions.last(2)
    assert_equal 8, instructions.length
    instructions, = compile(DeviceCgroup.rules_for)
    assert_equal %w[b400000000000000 9500000000000000], instructions.last(2)
    # The allow blocks: c*:* m, b*:* m, and the nine standard devices.
    assert_equal 11, instructions.count("b400000001000000")
  end

  def test_emulator_unions_removes_and_refuses_holes_like_cgroup_v1
    emulator = DeviceCgroup::Emulator.new
    emulator.apply(DeviceCgroup::DENY_ALL)
    emulator.apply("type" => "c", "major" => 1, "minor" => 3, "access" => "r", "allow" => true)
    emulator.apply("type" => "c", "major" => 1, "minor" => 3, "access" => "mw", "allow" => true)
    assert_equal ["c 1:3 rwm"], emulator.rules.map(&:cgroup_string)
    emulator.apply("type" => "c", "major" => 1, "minor" => 3, "access" => "w", "allow" => false)
    assert_equal ["c 1:3 rm"], emulator.rules.map(&:cgroup_string)
    emulator.apply("type" => "b", "major" => 8, "minor" => -1, "access" => "rw", "allow" => true)
    error = assert_raises(DeviceCgroup::Error) do
      emulator.apply("type" => "b", "major" => 8, "minor" => 1, "access" => "r", "allow" => false)
    end
    assert_equal "unable to remove 'allow' exception: requested rule [{98 8 1} r] not supported by devices cgroupv1 " \
                 "(cannot punch hole in existing wildcard rule [{98 8 -1} rw])", error.message
    # Removing a permission the wildcard does not hold is a no-op, not an error.
    emulator.apply("type" => "b", "major" => 8, "minor" => 1, "access" => "m", "allow" => false)
    assert_equal ["c 1:3 rm", "b 8:* rw"], emulator.rules.map(&:cgroup_string)
    emulator.apply(DeviceCgroup::ALLOW_ALL)
    assert_predicate emulator, :allow_all?
    assert_equal ["a *:* rwm"], emulator.rules.map(&:cgroup_string)
  end

  def test_permission_set_operations_canonicalise_order
    permissions = DeviceCgroup::Permissions
    assert_equal "rwm", permissions.union("mw", "r")
    assert_equal "rm", permissions.difference("mrw", "w")
    assert_equal "w", permissions.intersection("wm", "rw")
    assert permissions.valid?("rwm")
    refute permissions.valid?("mrw")
    refute permissions.valid?("x")
    assert permissions.empty?(permissions.difference("r", "r"))
  end

  def test_compiler_rejects_what_runc_rejects
    error = assert_raises(DeviceCgroup::Error) do
      DeviceCgroup.compile([DeviceCgroup::DENY_ALL, {"type" => "c", "major" => 2**32, "minor" => 1, "access" => "r", "allow" => true}])
    end
    assert_equal "invalid major 4294967296", error.message
    error = assert_raises(DeviceCgroup::Error) do
      DeviceCgroup.compile([{"type" => "p", "major" => 1, "minor" => 3, "access" => "rw", "allow" => true}])
    end
    assert_equal "cannot add rule [config.Rule{Type:112, Major:1, Minor:3, Permissions:\"rw\", Allow:true}] with non-cgroup type 'p'",
                 error.message
    # A major in [2^31, 2^32) is encoded with its bits intact (Go int32 conversion).
    instructions, = compile([DeviceCgroup::DENY_ALL, {"type" => "b", "major" => 2**32 - 1, "minor" => 0, "access" => "rwm", "allow" => true}])
    assert_includes instructions, "55040300ffffffff"
  end

  def test_an_empty_permission_rule_grants_nothing
    # containerd passes a CRI Device's permissions verbatim; an empty set is
    # an exception without any access, which the emulator drops.
    default, = compile(DeviceCgroup.rules_for)
    with_empty, = compile(DeviceCgroup.rules_for(devices: [{"type" => "c", "major" => 4, "minor" => 1, "access" => "", "allow" => true}]))
    assert_equal default, with_empty
  end
end

# One loaded program per rule set: containers with equal rules share it,
# differing rules do not, and the cache is bounded.
class DeviceCgroupAttacherCacheTest < Minitest::Test
  DeviceCgroup = Rubernetes::Platform::Linux::DeviceCgroup

  class FakeProgram
    attr_reader :id, :closed

    def initialize(id) = (@id = id) && (@closed = false)
    def close = @closed = true
  end

  class FakeBPF
    attr_reader :loaded, :attached

    def initialize
      @loaded = []
      @attached = []
    end

    def load(instructions:, program_type:, license:, expected_attach_type:, name:, resource_id:)
      @loaded << instructions.map(&:to_binary).join
      FakeProgram.new(@loaded.length)
    end

    def prog_attach(target_fd:, program:, attach_type:, flags:, resource_id:)
      @attached << [program.id, flags]
      true
    end
  end

  def test_equal_rule_sets_share_one_loaded_program_and_differing_sets_do_not
    bpf = FakeBPF.new
    attacher = DeviceCgroup::Attacher.new(bpf: bpf, cache_limit: 2)
    Dir.mktmpdir("devcg-cache-") do |directory|
      default = DeviceCgroup.rules_for
      assert_equal 1, attacher.attach(directory, default)
      assert_equal 1, attacher.attach(directory, DeviceCgroup.rules_for.map(&:to_h))
      assert_equal 2, attacher.attach(directory, DeviceCgroup.rules_for(privileged: true))
      assert_equal 3, attacher.attach(directory, DeviceCgroup.rules_for(devices: [{"type" => "c", "major" => 195, "minor" => 0, "access" => "rw", "allow" => true}]))
      assert_equal 3, bpf.loaded.length
      assert_equal 3, bpf.loaded.uniq.length
      assert_equal [[1, 2], [1, 2], [2, 2], [3, 2]], bpf.attached
      assert_equal 2, attacher.cached_rule_sets
      # The default set was evicted (LRU) and is loaded again on next use.
      assert_equal 4, attacher.attach(directory, default)
      assert_equal bpf.loaded[0], bpf.loaded[3]
    end
  end

  def test_guest_kernel_config_supports_the_program
    configs = Dir[File.expand_path("../../build/microvm/kernel/*.config", __dir__)]
    skip "no microvm guest kernel config built" if configs.empty?
    configs.each do |config|
      text = File.read(config)
      %w[CONFIG_BPF_SYSCALL=y CONFIG_CGROUP_BPF=y CONFIG_CGROUPS=y].each { |option| assert_includes text.lines.map(&:chomp), option, config }
    end
  end
end
